namespace Words
module WordsList =

    // print all entries on console
    // Array.iter (printfn "%A") Words.WordsList.wordsAndMeaningsSorted
    let wordsAndMeaningsSorted =
        [|
         ("Abasement", "humiliation; degradation")
         ("Abate", "reduce in intensity")
         ("Aberration", "deviation from the normal")
         ("Abeyance", "state of inactivity; disuse")
         ("Abhor", "hate")
         ("Abjure", "renounce; swear to refrain from something")
         ("Abraded", "worn away; eroded [abrade (v); abrasion (n)]")
         ("Abrasion",
          "1. damage to skin caused by scraping; 2. process of scraping or rubbing [abrade (v)]")
         ("Abrasive", "rough; coarse; harsh")
         ("Abrogate", "cancel; deny; repeal")
         ("Abscission", "cutting; process causing leaves to fall off")
         ("Absolution", "forgiveness; pardon; release")
         ("Abstain", "desist; go without; withdraw")
         ("Abstemious", "self denying; refraining from indulging")
         ("Abstruse", "difficult to understand; obscure")
         ("Abut", "to adjoin")
         ("Abysmal", "very deep; very bad")
         ("Accolade", "tribute; honor; praise")
         ("Accretion", "accumulation of matter; growth produced by adding from the outside")
         ("Acolyte", "disciple; follower or attendant")
         ("Acquiesce", "to agree to; give in to")
         ("Acrid", "sharp; pungent (used of smells and tastes)")
         ("Acrophobia", "fear of heights")
         ("Acuity", "sharpness (mental or visual)")
         ("Adamant", "forceful; inflexible")
         ("Adieu", "goodbye")
         ("Adjure", "command solemnly")
         ("Admonitory", "scolding [admonition (n)]")
         ("Adroit", "skilful / skillful")
         ("Adulation", "strong admiration; worship")
         ("Adumbrate", "outline; indicate")
         ("Adverse",
          "preventing success or development; harmful; unfavourable.
          e.g. taxes are having an adverse effect on production.
          synonyms:  hostile, inimical, unfriendly")
         ("Adversity", "hardship")
         ("Advocate", "support")
         ("Aesthetic", "concerning art or beauty")
         ("Affable", "friendly; social; easygoing")
         ("Affectation", "a deliberate pretense or exaggerated display")
         ("Agnostic",
          "a person who holds the view that any ultimate reality (as God) is unknown and probably unknowable; broadly : one who is not committed to believing in either the existence or the nonexistence of God or a God")
         ("Agog", "amazed; wide-eyed with enthusiasm")
         ("Aisle", "corridor; passageway (esp. between rows of seats)")
         ("Alacrity", "eagerness; enthusiasm; quickness")
         ("Alchemy", "medieval chemistry; attempt to change base metal into gold")
         ("Alibi", "an excuse that shows someone was not at a crime scene")
         ("Allay", "to lessen")
         ("Alleviate", "make less severe")
         ("Alleviated", "made less severe [alleviation (n); alleviate (v)]")
         ("Allure", "1. attraction (n); 2. to attract (v)")
         ("Aloof", "distant; detached; cold")
         ("Altruism", "putting others first; being self-sacrificing")
         ("Amalgamate", "join; consolidate [amalgamation (n)]")
         ("Amass", "accumulate")
         ("Ambidextrous", "able to use both left and right hands equally well")
         ("Ambiguity", "uncertainty; vagueness")
         ("Ambiguous", "unclear in meaning; can be interpreted in different ways")
         ("Ambivalence",
          "is a state of having simultaneous conflicting reactions, beliefs, or feelings towards someone or something")
         ("Ambulatory", "able to walk around (used of hospital patients)")
         ("Ameliorate", "make better")
         ("Amelioration", "improvement")
         ("Amiable", "friendly")
         ("Amity", "friendship")
         ("Amorphous", "lacking in shape")
         ("Amortize", "pay off a debt in installments")
         ("Anachronistic", "occurring in the wrong time period [anachronism (n)]")
         ("Analgesic", "medicine to combat pain")
         ("Analogous", "comparable")
         ("Analogue", "1. something similar; 2. output proportional to input (engineering)")
         ("Anarchy", "chaos; lack of government")
         ("Anecdote", "a brief amusing story")
         ("Animosity", "hatred; antagonism")
         ("Annex", "(v)	take possession of; seize; capture;
                    (n)	a building which is an addition to an existing building")
         ("Annulment",
          "the act of abrogating; an official or legal cancellation; the state of being cancelled or annulled; a formal termination")
         ("Anodized", "electroplated; coated with thin layer of metal")
         ("Anomaly", "something which does not fit in a pattern; irregularity")
         ("Antagonism", "hostility; strong opposition")
         ("Antagonistic", "opposed; hostile; aggressive")
         ("Antediluvian", "outdated; prehistoric; very old-fashioned")
         ("Anthology", "a book which is a collection of poems or stories")
         ("Anthropocentrism", "putting man at the center of one's philosophy")
         ("Antipathy", "hatred")
         ("Antiquated", "outdated; old fashioned")
         ("Apathetic", "indifferent; uninterested; lethargic")
         ("Apathy", "lack of interest or emotion")
         ("Aphoristic", "expressed tersely [aphorism (n) = short statement; maxim]")
         ("Apocryphal", "of doubtful origin")
         ("Apostrophe",
          "1. punctuation mark; 2. appeal to someone not present (a figure of speech)")
         ("Appease", "pacify; soothe; calm down; make peace with")
         ("Apposite", "fitting; suitable")
         ("Appraise",
          "assess the value or quality of; assess the performance of (an employee) formally; set a price on (by official valuer)")
         ("Apprehension", "slight fear; sense of something unfavorable")
         ("Apprehensive", "worried; fearful")
         ("Apprise", "inform somebody of something")
         ("Approbation", "approval [opp. disapprobation]")
         ("Arable", "can be cultivated")
         ("Arbitrary", "random; for no definite reason")
         ("Arbitration", "giving authoritative judgment")
         ("Arbitrator", "mediator; person appointed to judge a dispute [arbitrate (v)]")
         ("Arboreal", "living in trees; concerned with trees")
         ("Arcane", "obscure; known only to a few people")
         ("Archaic", "ancient; outdated; old fashioned")
         ("Archetype", "classic example of")
         ("Archives", "collections of old records; place of storage of old documents")
         ("Arduous", "hard")
         ("Armada", "fleet of ships")
         ("Arresting", "(a)	attracting attention; striking")
         ("Arson", "deliberate, criminal starting of fires")
         ("Articulate", "clear; lucid; eloquent")
         ("Artifice", "deception; trickery")
         ("Artisan", "craftsman")
         ("Artless", "without effort; without trickery; simple")
         ("Ascetic", "without luxuries; severely simple")
         ("Asperity", "using harsh or critical tone")
         ("Assay", "1. try; 2. assess purity")
         ("Assiduous", "thorough; diligent")
         ("Assuage", "to calm")
         ("Astute", "perceptive; sharp-witted")
         ("Asylum", "place of refuge or safety")
         ("Atavism", "reappearance of ancestral traits; regression [atavistic (a)]")
         ("Atheist", "person who does not believe in God")
         ("Atonement", "making amends for sin or crime [atone (v)]")
         ("Atrophy", "waste away from lack of use")
         ("Attenuate", "weaken")
         ("Augment", "increase; make bigger")
         ("Augury", "prediction, looking for omens [augur (v)]")
         ("Auspicious", "favorable; promising to turn out well")
         ("Austere", "severely plain")
         ("Avaricious", "greedy for money")
         ("Aver", "affirm")
         ("Aversion", "a dislike of")
         ("Baleful", "evil")
         ("Balk", "hinder and prevent; hesitate over")
         ("Balm", "soothing ointment or anything soothing [balmy (a)]")
         ("Banal", "common; dull")
         ("Banality", "ordinariness; dullness")
         ("Bane", "troublesome influence")
         ("Bard", "poet")
         ("Barrage",
          "extended gunfire to cover an attack; dam across river; deluge or information etc.")
         ("Bastion", "fortress; stronghold")
         ("Befuddle", "confuse")
         ("Begrudge", "resent")
         ("Beguile", "mislead; lure")
         ("Belabor", "explain in unnecessary detail")
         ("Beleaguer", "besiege; attack")
         ("Belie", "contradict")
         ("Belittle", "to demean")
         ("Bellicose", "war-like; aggressive")
         ("Belligerent", "aggressive; ready to fight")
         ("Bemoan", "complain about")
         ("Benevolent", "kindly")
         ("Benign", "kindly; harmless")
         ("Benignity", "compassion; gentleness; fondness")
         ("Bent", "(n)	inclination; aptitude")
         ("Bequeath", "leave something in one's will to be given after one's death")
         ("Berate", "scold; criticize")
         ("Beret", "type of cap")
         ("Bestial", "behaving like a beast; brutal")
         ("Bigot", "narrow-minded, prejudiced person")
         ("Bilk", "cheat; defraud")
         ("Billowing", "swelling; fluttering; waving")
         ("Blandishment", "words used to coax or flatter [blandish (v)]")
         ("Blasphemy", "speech which offends religious sentiments")
         ("Blatant", "obvious")
         ("Blighted", "damaged; destroyed; ruined")
         ("Blithe", "free-spirited; carefree")
         ("Blowhard", "boastful person")
         ("Blunderbuss", "1. ancient weapon (type of gun); 2. a clumsy person")
         ("Bode", "indicate by signs")
         ("Bolster", "support; prop up")
         ("Bombast", "arrogant, pompous language")
         ("Boor", "a crude uncouth ill-bred person lacking refinement; ill-mannered person [boorish (a)]")
         ("Boorish", "ill-mannered")
         ("Bourgeois", "middle class")
         ("Boycott", "refuse to have dealings with")
         ("Braggart", "someone who boasts")
         ("Brawny", "muscular")
         ("Brevity", "being brief")
         ("Bristle", "to show irritation")
         ("Broach", "start to discuss; approach")
         ("Brook", "1. small stream; 2. tolerate")
         ("Brusque", "blunt; abrupt")
         ("Bulwark", "fortification; barricade; wall")
         ("Bureaucracy", "officialdom")
         ("Bureaucrat", "An official of the government or administration")
         ("Burgeon", "grow; flourish; put forth new shoots")
         ("Burlesque", "1. comic play; 2. lampoon")
         ("Burnish", "polish")
         ("Buttress", "strengthen; support")
         ("Byline", "the line that tells you who wrote an article")
         ("Cacophony", "discordant loud noises")
         ("Cadge", "get by begging")
         ("Cajole", "coax")
         ("Caldron/Cauldron", "huge cooking pot")
         ("Calibrate", "mark an accurate scale on a device")
         ("Callow", "immature")
         ("Candid", "frank; honest")
         ("Candor", "frankness; openness")
         ("Canonical", "orthodox [canon (n) = set of accepted works]")
         ("Cant", "insincere talk")
         ("Cantankerous", "bad-tempered; quarrelsome")
         ("Capacious", "spacious")
         ("Capitulate", "surrender; give in to")
         ("Caprices", "whimsies; fancies")
         ("Capricious", "determined by chance or impulse rather than by necessity")
         ("Cardinal", "1. high ranking church official; 2. major, important")
         ("Caret", "punctuation mark signifying omission")
         ("Carping", "constant criticism")
         ("Carrion", "dead flesh; carcasses")
         ("Cartographer", "person who makes maps")
         ("Castigate", "scold strongly")
         ("Castigation", "verbal punishment")
         ("Cataclysmic", "violently disruptive [cataclysm (n)]")
         ("Catastrophic", "involving or causing sudden great damage or suffering")
         ("Catharsis", "purging of pent-up emotions; purging the body to stimulate evacuation of the bowels")
         ("Caucus", "type of private political meeting")
         ("Caulk", "treat with substance such as tar to make water-tight")
         ("Causality",
          "the principle of cause and effect; the source which causes an effect")
         ("Caustic", "burning")
         ("Cavalcade", "procession of vehicles")
         ("Celerity", "speed")
         ("Censorious", "disapproving; critical")
         ("Censure",
          "strong or vehement expression of disapproval; harsh criticism; blame")
         ("Centrifuge", "device to separate substances by spinning them at high speed")
         ("Centurion", "roman soldier (commander of a company of 100 soldiers)")
         ("Cerebral", "intellectual")
         ("Certitude", "certainty")
         ("Chantey", "type of song sung by sailors")
         ("Charlatan", "trickster who claims knowledge he doesn't have")
         ("Chary", "wary of; cautious about; reluctant to give")
         ("Chastises", "punishes")
         ("Chauvinist", "someone excessively patriotic [chauvinism (n)]")
         ("Chicanery", "trickery")
         ("Chimerical", "changeable; unstable")
         ("Choleric", "easily angered")
         ("Chorales", "simple hymns")
         ("Chronic",
          "long lasting (often used for diseases in which case the opposite is acute)")
         ("Chronicler", "person who records historical information")
         ("Churlishness", "rudeness; ill-mannered behavior")
         ("Circuitous", "indirect")
         ("Circumlocution", "using too many words; long-windedness")
         ("Circumscribe", "limit")
         ("Circumspect", "cautious; considering all sides")
         ("Circumvent", "avoid")
         ("Clairvoyant", "psychic; mystic")
         ("Clamor", "shout; scream")
         ("Clandestine", "secret; covert; stealthy")
         ("Clemency", "mercy")
         ("Cliché", "overused expression; something unoriginal")
         ("Clientele", "customers")
         ("Cloistered", "isolated")
         ("Cloture", "closure; terminating a debate by voting")
         ("Coalesce", "come together; merge")
         ("Cobble",
          "to put together roughly or clumsily; a small round stone used to cover road surface")
         ("Coda",
          "piece of music at the end of a musical work; finale; final part of document")
         ("Coddle", "pamper; fuss over; indulge")
         ("Codify",
          "to organize things like rules, laws, or principles into a code or system")
         ("Coerce", "force [coercion (n); coercing (a)]")
         ("Coercion", "force")
         ("Cogent", "lucid; well argued")
         ("Cogitate", "think over something; ponder")
         ("Cognitive", "concerned with thinking or perceiving [cognition (n)]")
         ("Colander", "bowl with holes used to drain vegetables etc.")
         ("Coleslaw",
          "a salad dish of shredded raw cabbage, carrots, and other vegetables mixed with mayonnaise")
         ("Collage", "picture made from fragments of other pictures")
         ("Collate", "arrange in order")
         ("Colloquial", "local and informal (used of language)")
         ("Collusion", "plotting and planning")
         ("Comeliness", "beauty; prettiness [comely (a)]")
         ("Comity", "a state or atmosphere of harmony or mutual civility")
         ("Commandeer", "take possession of")
         ("Commensurate", "corresponding in size or degree or extent; equal in significance")
         ("Commingle", "mix")
         ("Complacent", "self-satisfied; smug")
         ("Complaisance", "flexibility; willingness to please [complaisant (a)]")
         ("Compliant", "easy to control; submissive")
         ("Compromised",
          "1. damaged or put in doubt (esp. of reputation); 2. reached an agreement by giving up part of a claim")
         ("Concatenate", "link together")
         ("Concatenation", "linking into chains")
         ("Conciliate", "to bring together; end a dispute")
         ("Conciliation", "the act of placating and overcoming distrust and animosity")
         ("Concise", "stated in few words")
         ("Condescend", "talk down to")
         ("Condescension", "talking down to someone [condescending (a)]")
         ("Condone", "tacitly support; overlook")
         ("Condoning", "overlooking; disregarding; ignoring")
         ("Conflagration", "big fire")
         ("Conflate",
          "combine (two or more sets of information, texts, ideas, etc.) into one")
         ("Confound", "confuse")
         ("Congeal", "to solidify")
         ("Congenital", "present from birth")
         ("Congruent", "agreeing; accordant; congruous")
         ("Conniving", "cunning; scheming [connive (v)]")
         ("Connoisseur", "person with refined taste and good judgment")
         ("Conscript",
          "1. person enlisted compulsorily into the armed forces; 2. (v) to enlist compulsorily")
         ("Consecrate", "dedicate")
         ("Consensus", "general agreement")
         ("Conspicuous", "easily seen; prominent")
         ("Consternation", "worry and concern")
         ("Construe", "make sense of; assign a meaning to")
         ("Consummate", "complete; total; supremely good")
         ("Contemporary", "living or happening at the same time")
         ("Contention", "the act of competing as for profit or a prize")
         ("Contentious", "causing argument [contention (n); contend (v)]")
         ("Contiguous", "adjacent; touching; abutting [contiguity (n)]")
         ("Contrite", "sorry")
         ("Contrition", "sorrow and repentance")
         ("Contumacious", "stubborn")
         ("Contusion", "a bruise")
         ("Conundrum", "a puzzle")
         ("Conventional", "usual; customary; common")
         ("Cornucopia", "symbol (horn filled with fruit etc.) denoting natural abundance")
         ("Corpulent", "fat")
         ("Corroborate", "give supporting evidence [corroboration (n)]")
         ("Corrugated", "highly folded")
         ("Coterie", "clique; small group with common interests")
         ("Counterfeit", "fake; false")
         ("Covert", "hidden; undercover")
         ("Cower", "recoil in fear or servility; shrink away from")
         ("Credible", "believable")
         ("Creditable", "praiseworthy")
         ("Credulous", "gullible; ready to believe anything")
         ("Crepuscular", "active at dawn and dusk")
         ("Cringe", "recoil; flinch; shy away")
         ("Cryptic", "puzzling; enigmatic")
         ("Culpability", "guilt [culpable = blameworthy]")
         ("Cumbersome", "bulky; difficult to carry [encumber = to burden]")
         ("Curmudgeon", "grumpy person")
         ("Curtail", "cut short")
         ("Cynical", "believing that people act only out of selfish motives")
         ("Daguerreotype", "forerunner of the photograph")
         ("Dally", "waste time; flirt")
         ("Damp", "(used of vibration) reduce in extent")
         ("Daunt", "cause to lose courage")
         ("Dawdler", "slow person who falls behind others [dawdle (v)]")
         ("Debacle", "disaster")
         ("Debilitating", "weakening [debilitate (v)]")
         ("Debility", "weakness; incapacity")
         ("Debunking", "exposing false claims or myths")
         ("Decathlon", "an athletic competition with ten events")
         ("Decimated", "kill or destroy a large part of (originally one tenth)")
         ("Decorum", "dignified, correct behavior [decorous (a)]")
         ("Decoy", "lure; trap; trick")
         ("Deference", "courteous regard for people's feelings; respect")
         ("Deferential", "showing respect [deference (n); defer (v)]")
         ("Defoliate", "cause leaves to fall off")
         ("Defunct", "no longer in existence")
         ("Degradation", "deprivation; poverty; debasement")
         ("Deign", "condescend")
         ("Deleterious", "causing harm or damage")
         ("Deliberate", "done consciously and intentionally; careful and unhurried")
         ("Delineate", "represented accurately or precisely")
         ("Delineation", "demarcation; explanation; definition; outlining")
         ("Demagogue",
          "mob leader (who appeals to base instincts) [demagogy/demagoguery (n)]; a leader who makes use of popular prejudices and false claims and promises in order to gain power")
         ("Demur", "raise objections or show reluctance")
         ("Denigrate", "decry; criticize; belittle")
         ("Denounce", "condemn; speak out against")
         ("Deplete", "use up; lessen")
         ("Deplore", "regret")
         ("Depravity", "moral corruption")
         ("Deprecate", "criticize; denounce")
         ("Deride", "ridicule; make fun of; mock")
         ("Derision", "mockery [deride (v)]")
         ("Derogatory", "uncomplimentary")
         ("Descry", "to see (esp. at a distance); catch sight of")
         ("Desecrate", "to damage or pollute a holy place")
         ("Desecration", "spoiling something holy")
         ("Desist", "stop; discontinue; cease")
         ("Despondent", "having no hope; miserable")
         ("Destitution", "hardship; poverty; misery")
         ("Desultory", "aimless; inconsistent in effort")
         ("Deter", "put off; prevent")
         ("Deteriorate", "worsen; decline")
         ("Deterrent", "something immaterial that interferes with action or progress")
         ("Detrimental", "harmful")
         ("Devoured", "greedily eaten/consumed")
         ("Dexterity", "skill, esp. with hands [dexterous (a)]")
         ("Dexterous", "skilful with hands")
         ("Diaphanous", "transparent; thin and delicate")
         ("Diatribe", "tirade; violent denunciation; stream of criticism")
         ("Dichotomy", "a division into two parts")
         ("Didactic", "intended to teach; instructive")
         ("Diffident", "lacking confidence")
         ("Digress", "wander off the subject")
         ("Dike", "dam; embankment")
         ("Dilatory", "slow; falling behind with one's work")
         ("Dilemma", "puzzling situation")
         ("Dilettante", "person who dabbles in a subject without serious study")
         ("Dilettantism",
          "dabbling esp. in the arts [dilettante (n) = person who dabbles]")
         ("Diligent", "hard-working")
         ("Diorama", "model of a scene")
         ("Dirge", "mournful song")
         ("Disabuse", "make someone aware of an error in thinking")
         ("Disapprobation", "disapproval")
         ("Disarm", "1. take away weapons; 2. win over to one’s side [disarming (a)]")
         ("Disavow", "deny any responsibility or support for")
         ("Discern", "to distinguish one thing from another")
         ("Discernment", "judgment; perceptiveness")
         ("Discord", "disagreement")
         ("Discordancy", "cacophony; harshness; jarring")
         ("Discordant", "not in agreement or harmony")
         ("Discountenance", "disallow; refuse to approve of")
         ("Discrepancy", "something which does not match up; inconsistency")
         ("Discrete",
          "separate; discontinuous (not to be confused with discreet - prudent; diplomatic]")
         ("Discriminate", "to make a clear distinction; see the difference")
         ("Discursive",
          "passing aimlessly from one subject to another; digressive; rambling")
         ("Discursiveness", "long windedness; indirectness")
         ("Disdain", "contempt; strong dislike")
         ("Disingenuous",
          "not candid or sincere, typically by pretending that one knows less about something than one really does")
         ("Disinter", "dig up [opposite inter = bury]")
         ("Disinterested", "unbiased")
         ("Disparage", "criticize; belittle")
         ("Disparity", "an inequality")
         ("Dispassionate", "neutral; objective")
         ("Dispatch", "1. send (v); 2. speed; celerity (n)")
         ("Dissemble", "avoid the truth")
         ("Disseminating", "circulating; broadcasting; spreading (information)")
         ("Dissident", "person who disagrees [dissidence (n)]")
         ("Dissonance", "discord; disagreement")
         ("Distend",
          "cause to expand as it by internal pressure; Swollen; inflated; distended; puffed up")
         ("Diurnal", "active in daytime")
         ("Divert", "1. entertain; 2. distract; 3. cause a detour")
         ("Divest", "remove; take off")
         ("Docile", "gentle and easily lead")
         ("Doff", "take off (esp. of a hat)")
         ("Dogmatic", "having stubbornly held opinions")
         ("Dolt", "stupid person")
         ("Don", "put on (esp. of clothes)")
         ("Dormancy", "state of inactivity")
         ("Dotard", "foolish old man")
         ("Dote", "be excessively fond of [doting (a)]")
         ("Drabness", "dullness")
         ("Drawl", "speak slowly with words running together")
         ("Drivel", "nonsense")
         ("Droll", "dryly amusing")
         ("Drone", "1. monotonous noise (n); 2. to speak with no emotion (v); 3.male bee")
         ("Dross", "something worthless; impurities left after refining")
         ("Dubious", "doubtful")
         ("Dupe", "to fool someone")
         ("Duplicity", "cunning; deception; double dealing")
         ("Dynamic", "lively; vibrant; energetic")
         ("Ebullient", "very lively; cheerful; jovial; happy")
         ("Eccentric", "unusual; quirky; odd")
         ("Eclectic", "taking things from different sources")
         ("Eddy", "circular current")
         ("Edifice", "building; structure; construction")
         ("Efface", "wipe out; remove all trace of")
         ("Effete", "excessively self-indulgent, affected, or decadent")
         ("Efficacy", "effectiveness")
         ("Effigy", "a model of a person")
         ("Effrontery", "insolent or impertinent behaviour; shameless or impudent boldness")
         ("Effusive", "gushing; demonstrative")
         ("Egalitarianism", "belief in equality")
         ("Egregious", "outstandingly, obviously bad")
         ("Egress", "exit")
         ("Elaborate", "1. complex and detailed (a); 2. to expand on (v)")
         ("Elegy", "poem concerned with death; praise of a dead person")
         ("Ellipsis", "omission of essential words")
         ("Eloquent", "fluent and persuasive in speech")
         ("Elucidate", "make clear")
         ("Elusive", "hard to pin down")
         ("Emaciated", "very thin; withered")
         ("Emancipate", "set free")
         ("Embezzle", "defraud; steal")
         ("Emboss", "decorate with a raised design")
         ("Embroil", "involve in hostility or argument")
         ("Emerge", "come out; appear")
         ("Emollient", "softening (a); something which softens (n)")
         ("Empirical", "found by experiment or practice")
         ("Emulate", "to imitate something admired")
         ("Encomium", "praise")
         ("Endemic", "native to or confined to a certain region")
         ("Endorse", "give support or approval to")
         ("Endow", "give gift; provide with money etc.")
         ("Endurance", "staying power; patience; stamina")
         ("Enduring", "lasting")
         ("Enervate", "weaken")
         ("Enfranchise", "give voting rights")
         ("Engender", "cause")
         ("Engendering", "causing; bringing into being [engender (v)]")
         ("Enhance", "improve; make better or clearer")
         ("Enigma", "puzzle; mystery")
         ("Enigmatic", "puzzling [enigma (n)]")
         ("Enlist", "1. sign up for the army; 2. obtain")
         ("Ensconce", "establish firmly in a position")
         ("Enshroud", "cover")
         ("Enunciation", "clear pronunciation; accent; articulation")
         ("Envenom", "to cause bitterness and bad feeling")
         ("Epaulet", "shoulder decoration")
         ("Ephemeral", "short-lived")
         ("Epicure", "someone who appreciates good food and drink")
         ("Epigram", "short, witty saying")
         ("Epistemology", "theory of knowledge")
         ("Epistle", "a letter (form of communication)")
         ("Epistolary", "concerned with letters; through correspondence")
         ("Epitaph",
          "a phrase or form of words written in memory of a person who has died, especially as an inscription on a tombstone")
         ("Epithet", "phrase used as a label or to express the essential nature of")
         ("Epitomized", "typified; characterized; personified")
         ("Equivocal",
          "ambiguous; open to interpretation [equivocate (v), equivocation (n)]")
         ("Equivocate", "speak ambiguously; avoid telling the truth")
         ("Equivocation", "speaking ambiguously [equivocate (v), equivocal (a)]")
         ("Err", "make a mistake")
         ("Errant", "1. wandering; 2. wrong; 3. straying from accepted standards")
         ("Erratic", "wandering; irregular")
         ("Erudition", "learning; scholarly knowledge [erudite (a)]")
         ("Eschew", "shun; avoid")
         ("Esoteric", "obscure and difficult to understand")
         ("Esoterica", "obscure details")
         ("Espouse", "promote; take up; support")
         ("Etymology", "the study of word origins")
         ("Eulogy",
          "a speech or piece of writing that praises someone or something highly, especially a tribute to someone who has just died")
         ("Euphemism",
          "A euphemism is a generally innocuous word or expression used in place of one that may be found offensive or suggest something unpleasant. Some euphemisms are intended to amuse; while others use bland, inoffensive terms for things the user wishes to downplay")
         ("Euphony", "pleasant sounds")
         ("Evacuate", "vacate; empty; abandon")
         ("Evanescent", "short-lived [evanescence (n)]")
         ("Exacerbate", "make worse")
         ("Exacerbated", "made worse [exacerbate (v); exacerbation (n)]")
         ("Exact", "(v)	to demand; extort")
         ("Exasperated", "frustrated; annoyed")
         ("Exceptionable", "very bad (something which we should object to)")
         ("Exculpate", "free someone from blame; pardon; acquit")
         ("Execrable", "very, very bad")
         ("Exegesis", "scholarly explanation or interpretation")
         ("Exemplar", "model type [exemplary (a)]")
         ("Exemplary", "outstandingly good; setting a fine example")
         ("Exemplify", "clarify by giving an illustration of; to serve as a good example")
         ("Exhaustive", "complete and thorough")
         ("Exigency", "urgent matter; pressing need")
         ("Exonerates", "acquits; absolves; removes blame")
         ("Exorcism", "getting free/rid of; eliminating (especially demons)")
         ("Expatiate", "speak or write at great length")
         ("Expatriate", "refugee; emigrant; someone living away from his own country")
         ("Expedient", "convenient; practical")
         ("Expedite", "make faster")
         ("Expiate", "atone; make amends for")
         ("Exposition", "clear explanation")
         ("Expostulate", "offer strong objections; remonstrate")
         ("Extant", "still in existence (opposite of extinct)")
         ("Extemporize", "speak without preparation or rehearsal [extemporaneous (a)]")
         ("Extirpate", "wipe out totally")
         ("Extirpation", "wiping out; complete destruction [extirpate (v)]")
         ("Extol", "praise")
         ("Extradite", "deport from one country back to the home country")
         ("Extraneous", "irrelevant")
         ("Extrapolate", "extend; predict on the basis of known data")
         ("Extrinsic", "irrelevant; on the outside")
         ("Fabricated", "made up; false; manufactured [fabricate (v); fabrication(n)]")
         ("Facetious", "not intended to be taken seriously; cleverly amusing in tone")
         ("Faddish", "whimsical; following a fashion")
         ("Fallacious", "false")
         ("Fallacy", "wrong idea [fallacious (a)]")
         ("Fallible", "capable of making mistakes [fallibility (n)]")
         ("Fallow", "uncultivated")
         ("Falter", "hesitate; waver")
         ("Fanatical", "obsessive; fixated")
         ("Fanaticism", "passion; excessive devotion")
         ("Fastidious", "overly particular; finicky")
         ("Fatuous", "silly; foolish")
         ("Fawn", "behave in a sycophantic way; grovel [fawning (a)]")
         ("Façade", "1. front elevation of building, 2. false appearance or demeanor")
         ("Feasible", "possible and practicable")
         ("Feckless", "feeble; helpless; lacking in initiative")
         ("Fecund", "fertile")
         ("Feint", "pretended attack; a move intended to deceive")
         ("Felicitous", "apt, well-suited for the occasion; exhibiting an agreeably appropriate manner or style")
         ("Ferrous", "concerned with iron or its compounds")
         ("Fervent", "passionate")
         ("Fervid", "passionate")
         ("Fervor", "passion; enthusiasm")
         ("Fickle", "unpredictable; whimsical; easily swayed")
         ("Figurehead", "symbol of power; nominal leader")
         ("Filibuster", "delaying tactics")
         ("Finesse", "skill")
         ("Firmament", "the sphere on which celestial bodies appear to be projected")
         ("Fitful", "not continuous; stopping and starting")
         ("Flag", "(v) 1. to lose energy; 2. to signal")
         ("Flagrant", "clearly wrong")
         ("Flail",
          "1. tool used to thresh grain; 2. to thresh (separate grain from chaff); 3. to wave arms about wildly")
         ("Flamboyant", "showy; ornate")
         ("Flaunt", "show off; display in a showy manner")
         ("Fledge",
          "1. grow feathers; 2. leave nest [fledgling (n) = an inexperienced person or a baby bird]")
         ("Flippant", "making jokes about serious matters")
         ("Flout", "defy; reject")
         ("Flustered", "worked-up; not calm")
         ("Fly-by-night", "unreliable; disreputable")
         ("Foible", "quirk; minor weakness")
         ("Foment", "1. stir up; 2. bathe with hot liquids (medical)")
         ("Foolhardy", "reckless [foolhardiness (n)]")
         ("Foppish",
          "behaving or dressing like a dandy; excessively concerned with fashion")
         ("Forage", "search for food")
         ("Forbearing", "tolerant [forbear (v); forbearance (n)]")
         ("Forensic", "concerned with argument or debate (esp. for legal evidence)")
         ("Foreshadowed", "indicated a future event [foreshadow (v)]")
         ("Fortitude", "bravery")
         ("Fortuitous", "happening by chance")
         ("Fracas", "fight; disturbance")
         ("Fractious", "irritable; difficult to control")
         ("Fraudulent", "fake; false")
         ("Frieze", "decorative border")
         ("Fringe", "1. decorative border with tassels (n); 2. to form an edge (v)")
         ("Frivolous", "not serious")
         ("Froward", "stubborn; wayward; disobedient")
         ("Frugal", "economical; not wasting anything")
         ("Fulminate",
          "1. attack loudly in words; denounce thunderously; 2. explode noisily")
         ("Furrow", "groove")
         ("Furtive", "hidden and secret")
         ("Fusillade", "long burst of gunfire")
         ("Futile", "useless; hopeless")
         ("Gaffe", "blunder; social mistake")
         ("Gainsay", "contradict")
         ("Gall",
          "1. bitterness (bad feeling); 2. confidence; 3. abnormal growth on a plant")
         ("Galleon", "ancient type of sailing ship")
         ("Gambit", "opening move; transaction")
         ("Gambol", "frolic; leap; bound")
         ("Gamut", "a complete extent or range")
         ("Garble", "distort; confuse; muddle")
         ("Garish", "gaudy")
         ("Garner", "gather; collect")
         ("Garrulous", "talkative")
         ("Gaucherie", "awkwardness [gauche (a)]")
         ("Gaunt", "emaciated; bony and angular")
         ("Gavel", "judge’s hammer")
         ("Genre", "a category; type")
         ("Germane", "relevant")
         ("Germinal", "just growing; not developed; immature")
         ("Gerontocracy",
          "government by a council of elders; a governing body consisting of old people")
         ("Gibbering", "making meaningless noises")
         ("Gist", "essence; main point")
         ("Glacial", "hostile; unfriendly; cold; icy")
         ("Glib", "slick; superficial esp. in speech")
         ("Goad", "prod; urge")
         ("Gossamer", "delicate; filmy; like gauze")
         ("Gouge", "cut or dig out; to extort from, swindle, or overcharge")
         ("Grate", "(v)	1. to annoy; aggravate; vex; 2. shred")
         ("Gratis", "free of charge; without payment")
         ("Gratuitous", "unwarranted")
         ("Gravity", "seriousness")
         ("Gregarious", "extroverted; sociable; outgoing")
         ("Gregariousness", "sociability; liking for crowds [gregarious (a)]")
         ("Gritty", "coarse; granular")
         ("Guffaw", "sudden loud laughter")
         ("Guile", "cunning; craftiness")
         ("Guileless", "frank; straightforward; honest")
         ("Gullibility", "unwariness; trustfulness; being easily fooled")
         ("Gullible", "easily fooled")
         ("Gustatory", "concerned with the sense of taste")
         ("Hack", "1. chop roughly; 2. person who writes to earn money, 3. hired horse")
         ("Hackneyed", "common and over-used")
         ("Halcyon", "peaceful and happy; calm (esp. of summer weather)")
         ("Hallow", "respect; worship")
         ("Hallowed", "worshiped/worshipped; consecrated")
         ("Hamper", "hinder; obstruct")
         ("Hangar", "storage area (like garage) for a plane")
         ("Hapless", "unlucky")
         ("Harangue", "noisy, attacking speech; a loud bombastic declamation expressed with strong emotion")
         ("Harbingers", "indicators; bringers of warnings")
         ("Hasten", "hurry; accelerate; rush")
         ("Haughtiness", "arrogance; pride")
         ("Hawser", "thick rope or cable")
         ("Headstrong", "stubborn; willful")
         ("Hedonism", "self indulgence; pleasure-seeking")
         ("Hedonist", "a pleasure seeker")
         ("Heed", "listen to")
         ("Hegemony", "political domination; complete authority")
         ("Heresy", "against orthodox opinion")
         ("Heterodox", "unorthodox")
         ("Hiatus", "interruption; pause")
         ("Hidebound", "rigid in opinions")
         ("Hieroglyphics",
          "1. picture writing; 2. writing which is difficult to read or enigmatic")
         ("Hinder", "obstruct")
         ("Histrionic", "theatrical; exaggerated")
         ("Hoary", "old")
         ("Homiletics", "art of preaching and giving sermons")
         ("Homogeneity", "evenness; uniformity")
         ("Hone", "sharpen; increase; whet")
         ("Hortatory", "encouraging; exhorting")
         ("Hyperbole", "grossly exaggerated speech")
         ("Hypochondriac", "a person obsessed with health; having imaginary illnesses")
         ("Hypocritical", "insincere")
         ("Iconoclast", "person who opposes orthodoxy")
         ("Idiosyncrasy", "a personal peculiarity; something unique to an individual")
         ("Idyll", "story or incident in peaceful or ideal setting [idyllic (a)]")
         ("Ignominious", "shameful; disgraceful; inglorious; deserving or causing public disgrace or shame")
         ("Ignominy", "shame [ignominious (a) = shameful]")
         ("Illuminate", "to light up or make clear")
         ("Illusory", "deceptive; false; misleading")
         ("Immoderate", "excessive; extreme")
         ("Immutable", "unchanging; permanent")
         ("Impartial", "unbiased; neutral")
         ("Impecunious", "having no money")
         ("Impeding", "hindering [impede (v); impediment (n)]")
         ("Imperative", "must be obeyed")
         ("Imperturbability",
          "quality of being calm and not easily disturbed [imperturbable (a)]")
         ("Impious", "wicked; profane")
         ("Importune", "beg; solicit [importunate (a)]")
         ("Impoverished", "destitute; poor")
         ("Improbity", "lack of honesty or integrity")
         ("Impromptu", "unrehearsed; spontaneous")
         ("Impropriety", "inappropriate behavior")
         ("Impugn", "challenge; question someone’s honor etc.")
         ("Impugned", "challenged; called into question")
         ("Inadvertent", "not intentional")
         ("Incantation", "chant; invocation; prayer")
         ("Incarceration", "putting in prison")
         ("Incessant", "without stopping")
         ("Inchoate", "undeveloped; nascent")
         ("Incipient", "just beginning")
         ("Incise", "cut into [incision (n); incisive (a)]")
         ("Inclination", "tendency; a leaning toward")
         ("Incoherent", "not clear")
         ("Incongruous", "not fitting in; out of place")
         ("Inconsequential", "unimportant; insignificant; negligible")
         ("Inconspicuous", "not easily seen; subtle; not noticeable")
         ("Incubus", "encumbrance; nightmarish thing")
         ("Incumbents", "occupiers of a job or position")
         ("Indecorous", "unseemly; inappropriate (of behavior)")
         ("Indelible", "cannot be removed or erased")
         ("Indicted", "accused (of crime)")
         ("Indifferent", "1. neutral; 2. not outstanding")
         ("Indigence", "poverty")
         ("Indigenous", "native to a particular area")
         ("Indigent", "poor; needy [indigence (n)]")
         ("Indolence", "laziness")
         ("Inductee", "novice; beginner")
         ("Indulgent", "pampering; satisfying desires")
         ("Inebriation", "drunkenness; intoxication")
         ("Ineffable", "cannot be expressed in words")
         ("Inefficacious", "ineffective; not able to produce the desired effect")
         ("Inept", "incompetent; unskilled; useless")
         ("Inerrancy", "lack of error; infallibility")
         ("Inertia", "inactivity; lethargy")
         ("Inevitable", "cannot be avoided")
         ("Inexorable", "relentless")
         ("Inexpedient", "not advisable")
         ("Infallible", "perfect; flawless; cannot make mistakes")
         ("Infamous", "famous for something bad")
         ("Infer", "deduce; conclude")
         ("Ingenious", "very smart or clever : having or showing ingenuity")
         ("Inglorious", "shameful; disgraceful")
         ("Ingrate", "ungrateful person")
         ("Ingénue", "naïve, unsophisticated person")
         ("Inimical", "hostile")
         ("Iniquitous", "evil; unjust [iniquity (n)]")
         ("Injunction",
          "a court order requiring a person to do or cease doing a specific action.")
         ("Innate", "inherited; inborn")
         ("Innocuous", "harmless; inoffensive")
         ("Innovate", "create; introduce something new")
         ("Inscrutability", "quality of being difficult to comprehend [inscrutable (a)]")
         ("Inscrutable", "mysterious; impenetrable")
         ("Insentient", "unfeeling")
         ("Insipid", "dull; bland; boring")
         ("Instigate", "to start; provoke")
         ("Instigator", "troublemaker; person who entices others to do something")
         ("Insurgent", "a rebel")
         ("Intangible", "cannot be touched; abstract [intangibility (n)]")
         ("Intelligible", "can be understood")
         ("Intemperate", "excessive; immoderate [intemperance (n)]")
         ("Interminable", "never-ending")
         ("Intermittent", "sporadic; irregular")
         ("Interregnum", "interval between reigns or governments")
         ("Intractability", "stubbornness; resistance [intractable (a)]")
         ("Intransigence", "stubbornness")
         ("Intransigent", "stubborn; unyielding")
         ("Intrepid", "brave")
         ("Inured", "hardened; habituated")
         ("Inveigle", "coax; cajole; wheedle; entice")
         ("Inveterate", "habitual")
         ("Invidious", "arousing envy")
         ("Inviolable", "cannot be invaded")
         ("Irascible", "easily angered")
         ("Ire", "anger [irate (a) = very angry]")
         ("Irksome", "annoying; infuriating")
         ("Ironclad", "cannot be altered; firm")
         ("Ironic", "satiric; unexpected")
         ("Irrational", "unreasonable; absurd")
         ("Irreproachable", "cannot be criticized; perfect")
         ("Irrevocable", "cannot be canceled/cancelled; unchangeable")
         ("Itinerant", "nomadic; wandering from place to place")
         ("Jaded", "tired; bored; worn out")
         ("Jamb", "door post")
         ("Jargon", "specialized language used by experts")
         ("Jaundiced", "cynical; pessimistic")
         ("Jaunt", "short pleasure trip")
         ("Jeopardize", "put at risk; endanger")
         ("Jibe",
          "agree with; complement; match up with (in British usage jibe means mock)")
         ("Jingoistic", "extremely patriotic; nationalistic")
         ("Jockey",
          "(n) a person who rides in horse races, especially as a profession;
          (v) struggle by every available means to gain or achieve something")
         ("Jockeying", "maneuvering; struggling to get ahead of others [jockey (v)]")
         ("Jocular", "in a joking manner")
         ("Jollity", "gaiety; happiness")
         ("Jubilant", "ecstatic; delighted; rejoicing")
         ("Judicious", "correct in judgment; wise")
         ("Jurisprudence", "science or study of law")
         ("Juxtapose", "place next to")
         ("Kindle", "to start a fire")
         ("Knotty", "complex; difficult to solve")
         ("Labile", "changing rapidly; unstable")
         ("Labyrinth", "a maze")
         ("Labyrinthine", "complicated; highly convoluted")
         ("Laceration", "a cut")
         ("Lachrymose", "tearful; sad")
         ("Lackluster", "dull; monotonous; bland")
         ("Laconic", "using few words; brief; to the point")
         ("Lacuna", "gap; missing part [plural = lacunae]")
         ("Lambaste", "attack verbally")
         ("Lamentation", "expression of regret or sorrow")
         ("Lampoon", "ridicule; spoof")
         ("Lance", "spear; spike; javelin")
         ("Languid", "tired; slow")
         ("Languish", "decay; fade away; get weaker")
         ("Larceny", "theft; robbery; stealing")
         ("Largess", "generosity")
         ("Lassitude", "lack of energy; weariness")
         ("Latent",
          "hidden; potentially existing but not presently evident or realized;
          e.g. About a third of the world has latent tuberculosis, experts estimate; it usually becomes active when an infected person’s immune system is depressed.")
         ("Laud", "praise")
         ("Lavish", "on a grand scale; wasteful")
         ("Lax", "careless; not strict")
         ("Leaven", "to make light; modify; cause bread to rise using yeast etc.")
         ("Legend", "1. key to map; 2. myth or story")
         ("Legion", "in large numbers")
         ("Lethargic", "tired; without energy")
         ("Levee", "1. raised bank of a river; 2. morning reception held by a monarch")
         ("Levity", "flippancy; joking about serious matters")
         ("Libertarian", "someone who opposes tyranny")
         ("Libertine", "dissolute person; prodigal")
         ("Lien", "right to sell property held as a security; legal hold on job etc.")
         ("Limerick", "short amusing poem")
         ("Limpid", "transparently clear")
         ("Liniment", "soothing lotion")
         ("Lint", "fluff; soft material used to cover wounds")
         ("List", "v)	1. to lean to one side; 2. to write in order")
         ("Lithe", "flexible; supple")
         ("Liturgy", "form of worship")
         ("Livid", "very angry")
         ("Lobbyist",
          "person who tries to persuade someone to support a particular cause")
         ("Lofty", "snooty; arrogant; haughty")
         ("Loll", "laze around; hang out (when used of the tongue)")
         ("Longevity", "long life")
         ("Longshoreman", "is a worker who loads and unloads cargo onto ships. These workers are also known in the United Kingdom as 'dockers', in continental Europe as 'stevedores' and more generally as dockworkers")
         ("Loom", "come into view indistinctly, often threateningly")
         ("Lope", "run with long strides")
         ("Loquacious", "talkative")
         ("Lucid", "clear")
         ("Ludicrous", "ridiculous; silly")
         ("Lugubrious", "sad; gloomy")
         ("Lukewarm", "1. unenthusiastic; 2. neither hot nor cold")
         ("Lumber", "1. walk in an ungainly way; 2. timber (wood)")
         ("Luminary", "eminent person")
         ("Lummox", "clumsy person")
         ("Luscious", "juicy; moist; succulent")
         ("Lynch", "assassinate; kill; illegal hanging")
         ("Macerate", "soften or break up by soaking; weaken")
         ("Machinations", "plots and plans")
         ("Maculated", "spotted; stained")
         ("Maelstrom", "whirlpool; storm in the ocean")
         ("Magnanimous", "generous; big-hearted")
         ("Magnate", "powerful businessman")
         ("Maladroit", "clumsy; unskillful")
         ("Malady", "illness")
         ("Malapropism", "use of similar sounding but incorrect word")
         ("Malediction", "a curse")
         ("Malefactor", "a wrong-doer")
         ("Malevolent", "having evil intentions [malevolence(n)]")
         ("Malign", "slander")
         ("Malinger", "deliberately avoid work; shirk")
         ("Malleable", "flexible; can be shaped")
         ("Mallet", "1. wooden hammer; 2. stick used for polo")
         ("Manipulatable", "influenceable; controllable")
         ("Manipulative", "scheming")
         ("Mannered", "stylized; pretentious")
         ("Marred", "damaged; spoiled")
         ("Marshal", "to gather together")
         ("Marsupial", "non-placental mammal whose members are born incompletely developed and are typically carried and suckled in an external pouch on the mother ---  e.g. kangaroos, koala, tasmanian devil, opossums, bandicoots, wombats")
         ("Martinet", "person who believes in strict discipline")
         ("Masochist", "person who intentionally inflicts pain on himself")
         ("Matriarchy", "society governed by women")
         ("Maudlin", "sad; sentimental; inclined to weep")
         ("Maverick", "a loner")
         ("Meager", "in short supply")
         ("Meander", "wander from side to side")
         ("Mellow", "soft; melodious; ripe")
         ("Menagerie", "collection of animals")
         ("Mendacious", "given to lying")
         ("Mercenary", "concerned only with money")
         ("Mercurial", "volatile; changeable")
         ("Meretricious", "falsely attractive; tawdry; tastelessly showy")
         ("Merge", "come together")
         ("Metaphorically", "symbolically; figuratively")
         ("Meticulous", "very careful; painstaking")
         ("Mettle", "courage; bravery; valor")
         ("Mettlesome", "spirited [mettle (n)]")
         ("Milieu", "environment")
         ("Milk", "to squeeze; obtain by application of pressure")
         ("Millinery", "hats and hat-making")
         ("Minatory", "threatening")
         ("Mince",
          "1. chop into small pieces; 2. walk with tiny steps, 3. speak in an affected manner")
         ("Minion", "underling; servant")
         ("Minutiae", "small details")
         ("Mire", "swamp; muddy ground")
         ("Misanthrope", "hater of the rest of mankind")
         ("Misconstrue", "put a wrong interpretation on something")
         ("Misnomer", "wrong name")
         ("Misogynist", "hater of women")
         ("Misrepresentation", "deliberately deceiving")
         ("Mitigate", "lessen; make less severe")
         ("Modest", "1. bashful; unpretentious; 2. not excessive")
         ("Modicum", "small amount")
         ("Momentous", "very important")
         ("Monolithic", "united in purpose; forming a single unit")
         ("Monotonous", "dull; unvarying")
         ("Moralistic", "concerned with morals [moralize (v)]")
         ("Moratorium", "temporary prohibition or halt to activity")
         ("Moribund", "on the point of death")
         ("Morose", "gloomy; bad tempered")
         ("Mundane", "ordinary; worldly")
         ("Munificent", "generous; charitable")
         ("Muse",
          "1. think; meditate (v); 2. a source of inspiration (n) [in mythology, a goddess who gives inspiration]")
         ("Mutinous", "very rebellious")
         ("Myriad", "in large numbers")
         ("Nadir", "lowest point")
         ("Narcissistic", "having an inflated idea of one's own importance")
         ("Nascent", "emerging; newly formed")
         ("Natty", "neat; dapper; smart")
         ("Navigable", "suitable for sailing")
         ("Nebulous", "vague")
         ("Nefarious", "wicked; immoral; disreputable")
         ("Negate", "cancel; deny")
         ("Negligence", "carelessness")
         ("Neologism", "newly coined word")
         ("Neophyte", "new convert; tyro")
         ("Nettle", "annoy")
         ("Nexus", "connection")
         ("Niggardly", "miserly; stingy")
         ("Noisome", "disgusting")
         ("Nomadic", "wandering from place to place")
         ("Nonchalance", "an appearance of indifference; calm and composed")
         ("Nondescript", "having no special features; dull and ordinary")
         ("Nonentity", "a person of no importance; not famous")
         ("Nonplussed", "confused")
         ("Nostalgia", "longing for the past")
         ("Nostrum", "remedy")
         ("Notoriety", "infamy; known for wrong doing")
         ("Novel", "new; unusual")
         ("Novice", "a beginner; tyro")
         ("Noxious", "harmful; poisonous; lethal")
         ("Nuance", "something subtle; a fine shade of meaning")
         ("Nugatory", "of minor significance; futile")
         ("Nullify", "to counter; make unimportant")
         ("Nuzzle", "cuddle; snuggle")
         ("Obdurate", "stubborn")
         ("Obfuscate", "deliberately make something difficult to understand")
         ("Objective", "unbiased; not subjective")
         ("Obligate", "compulsory")
         ("Oblique", "indirect; slanting")
         ("Obliterate", "destroy; demolish; eradicate")
         ("Oblivious", "totally unaware")
         ("Obloquy", "a false accusation of an offense")
         ("Obscure", "difficult to understand; partially hidden")
         ("Obscured", "hidden; covered; buried")
         ("Obsequious", "attempting to win favor from influential people by flattery; servile; submissive")
         ("Obsession", "a dominating concern")
         ("Obsolete", "no longer valid")
         ("Obstreperous", "noisy and boisterous")
         ("Obtrude", "push to thrust outward")
         ("Obtuse", "mentally dull; of an angle, between 90 and 180 degrees")
         ("Obviate", "avoid; make unnecessary")
         ("Occluded", "obscured; blocked")
         ("Odious", "hateful")
         ("Odometer", "instrument to measure distance covered")
         ("Officious", "domineering; intrusive; meddlesome")
         ("Ogle", "stare at; observe in an obvious manner")
         ("Olfactory", "concerned with the sense of smell")
         ("Ominous", "threatening")
         ("Omnipotent", "all-powerful")
         ("Omniscient", "all-knowing")
         ("Onerous", "burdensome; hard to undertake")
         ("Onus", "burden")
         ("Opaque", "does not let light through")
         ("Opprobrious", "expressing great scorn [opprobrium (n)]")
         ("Opulent", "wealthy; rich; magnificent")
         ("Orate", "speak in a pompous manner")
         ("Ordain", "1. destine; 2. confer holy orders on a priest")
         ("Ornate", "highly decorated")
         ("Orthodox", "conventional")
         ("Ossified", "turned to bone; become rigid [ossification (n)]")
         ("Ossify", "1. turn to bone; 2. become fixed and rigid")
         ("Ostentatious", "showy")
         ("Ostracism", "shunning; social isolation [ostracize (v)]")
         ("Oust", "push out of a position")
         ("Outlier", "an extreme deviation from the mean")
         ("Overt", "obvious; not hidden")
         ("Overwrought", "worked up; in an emotional state")
         ("Oxymoron",
          "is a figure of speech that juxtaposes elements that appear to be contradictory.
          examples: 'working vacation' or 'instant classic'")
         ("Paean", "praise; tribute (esp. in song)")
         ("Palatable", "good to eat; agreeable")
         ("Palisade", "fence made of posts")
         ("Palliative", "a remedy that improves but doesn't cure")
         ("Pallid", "pale")
         ("Palpable", "easily felt; capable of being perceived")
         ("Palpate", "medical term meaning to examine with the hands")
         ("Panacea", "remedy for all ills")
         ("Panegyric", "speech praising someone; laudatory words")
         ("Papyrus", "material used for writing on before paper was invented")
         ("Paradigm", "1. example; 2. model; 3. way of looking at things")
         ("Paradox", "apparently contradictory statement")
         ("Paragon", "a perfect example")
         ("Paramount", "of supreme importance")
         ("Paranoia", "mental state characterized by delusions or excessive fear")
         ("Parasite", "1. scrounger; 2. animal which takes digested food from another")
         ("Parched", "dried up")
         ("Parenthesis",
          "remarks deviating from the main point [parentheses are round brackets in punctuation]")
         ("Pariah", "an outcast from society")
         ("Parish", "A local church community")
         ("Parity", "equality")
         ("Parlance", "a manner of speaking natural to a language's native speakers")
         ("Parley", "a negotiation between enemies")
         ("Parochial", "narrow-minded; concerned only with local matters; relating to or supported by or located in a parish")
         ("Parody", "a mockery; imitation for ridicule; spoof")
         ("Parry",
          "to ward off (a thrust, stroke, weapon, etc.), as in fencing; avert; to turn aside; evade or dodge")
         ("Parsimonious", "economical; frugal; thrifty; excessively unwilling to spend")
         ("Partiality", "bias")
         ("Partisan", "biased; one-sided; committed to one group")
         ("Pastiche",
          "work (usually artistic) which imitates, or is composed of parts taken from varied sources")
         ("Pathos", "evoking sadness or pity")
         ("Patron", "one who give support (usually financial)")
         ("Patronize", "1. to talk down to; condescend; 2. to be a customer of")
         ("Paucity", "shortage")
         ("Peccadillo", "minor weakness; trivial offense/offence")
         ("Pedagogy", "science of education; teaching")
         ("Pedant", "person who insists on strict adherence to rules or narrow learning")
         ("Pedantic", "over-insistent on matters of book-learning [pedant (n)]")
         ("Pedestrian", "common; mundane; banal")
         ("Peer", "1. an equal; 2. to stare at; 3. nobleman")
         ("Peerless", "without equal")
         ("Pejorative", "derogatory")
         ("Pellucid", "transmitting light; able to be seen through with clarity")
         ("Penchant", "inclination; leaning; tendency; predilection")
         ("Pensive", "in a thoughtful mood; thinking deeply")
         ("Penury", "poverty")
         ("Perceptive", "observant")
         ("Percipient", "perceptive; insightful")
         ("Perdition", "damnation")
         ("Peremptory", "in a commanding manner")
         ("Perennial", "long-lasting")
         ("Perfidious", "tending to betray")
         ("Perfidy", "treachery")
         ("Perfunctory", "superficial; cursory")
         ("Peripatetic", "nomadic; moving from place to place")
         ("Peripheral", "on the edge; not important")
         ("Perjury", "telling lies under oath")
         ("Pernicious", "destructive; harmful")
         ("Perpetuated", "caused to continue")
         ("Perpetuity", "eternity")
         ("Persevere",
          "continue in a course of action even in the face of difficulty or with little or no indication of success")
         ("Persnickety", "fastidious; fussy")
         ("Personable", "attractive")
         ("Personification",
          "1. represent something as a person; 2. a concrete example of")
         ("Perspicacious", "insightful; sharp; wise")
         ("Perspicacity", "insight")
         ("Pertain", "be relevant to [pertinent (a)]")
         ("Pertinent", "relevant")
         ("Peruse", "read carefully")
         ("Pervasive", "spreading everywhere")
         ("Petrify", "1. terrify; 2. turn to stone")
         ("Petulant", "sulky; peevish")
         ("Phenomenology",
          "branch of science concerned with things as they are perceived; not directly derived from theory")
         ("Phenomenon", "an event or happening (plural: phenomena)")
         ("Philanthropy", "charity; love of mankind")
         ("Philistine", "uncultured person")
         ("Phlegmatic", "having an unemotional and stolidly calm disposition; imperturbable; showing little emotion")
         ("Picayune", "insignificant; of little value")
         ("Pied", "multicolored")
         ("Pillage", "plunder")
         ("Pine", "1. type of evergreen tree; 2. grieve")
         ("Pinnacle", "topmost point")
         ("Pious", "very religious")
         ("Pique", "1. annoyance (n); 2. to stimulate interest; to annoy (v)")
         ("Pith", "center; soft part of stem; essence")
         ("Pivotal", "of central importance")
         ("Placate", "pacify; soothe; calm")
         ("Placebo", "harmless medicine with no effect; dummy medicine")
         ("Placid", "calm; peaceful")
         ("Plagiarism", "taking credit for someone else's writing or ideas")
         ("Plaintiff", "petitioner (in court of law)")
         ("Plaintive", "sad; mournful")
         ("Plaque",
          "1. surface deposit on teeth or in artery etc.; 2. decorative plate or sign")
         ("Platitude", "unoriginal, obvious saying")
         ("Plaudit", "statement giving strong praise")
         ("Plausibility", "believability [plausible (a)]")
         ("Plausible", "can be believed; reasonable")
         ("Plethora", "an excess")
         ("Pliable", "flexible; not stubborn")
         ("Plodding", "walking slowly and heavily; uninspired")
         ("Pluck", "(n)	courage")
         ("Plumage", "feathers of a bird")
         ("Plumb", "measure depth of (v); exact (a. slang)")
         ("Plummet", "fall suddenly and steeply")
         ("Podium", "raised platform")
         ("Poignant", "deeply moving; strongly affecting the emotions")
         ("Poised", "calm; collected; self-possessed")
         ("Polemical", "causing debate or argument")
         ("Ponderous", "weighty; slow and heavy")
         ("Pontificate", "speak pompously or dogmatically")
         ("Portend", "foretell")
         ("Portent", "a warning sign; omen")
         ("Poseur", "someone who puts on an act")
         ("Posterity", "future generations")
         ("Posthumous", "after death")
         ("Postulate", "hypothesize; propose")
         ("Posture", "(v)	to put on an act")
         ("Potable", "suitable for drinking")
         ("Potent", "powerful; compelling; strong")
         ("Pragmatic", "practical")
         ("Pragmatist", "practical person; one who is concerned with usefulness")
         ("Prattle", "speak about unimportant matters rapidly and incessantly; mindless talk")
         ("Preamble", "introductory material")
         ("Precarious", "unstable; risky")
         ("Precedent", "a previous occurrence used as a guide")
         ("Precept", "guiding principle")
         ("Precinct", "district of a city")
         ("Precipice", "steep slope")
         ("Precipitate", "bring about abruptly; e.g. the incident precipitated a political crisis; insoluble product of a reaction in chemistry")
         ("Precipitous", "done in a hurry")
         ("Preclude", "prevent or make impossible")
         ("Precocious", "developing early")
         ("Predecessor", "one who came before")
         ("Predicament", "dilemma; difficult situation")
         ("Predilection", "leaning; interest; talent")
         ("Preeminent", "famous; outstanding")
         ("Prerogative", "right or privilege")
         ("Presage", "forewarn of; indicate")
         ("Prescient", "having fore-knowledge")
         ("Presentiment", "a feeling that something might happen")
         ("Presumptuous", "assuming too much; arrogant")
         ("Pretension", "assumed attitude of superiority; arrogance")
         ("Pretentious", "pompous; self-important")
         ("Preternatural", "unnatural; abnormal")
         ("Prevaricate",
          "speak misleadingly and evasively; be deliberately ambiguous or unclear")
         ("Primordial", "present from the beginning of time")
         ("Pristine", "unspoiled")
         ("Probity", "uprightness; honesty")
         ("Proclivity", "tendency towards")
         ("Procrastinate", "delay; put off")
         ("Prodding", "a verbalization that encourages you to attempt something")
         ("Prodigal", "wasteful; extravagant")
         ("Prodigious", "very large")
         ("Profane", "unholy")
         ("Profanity", "swearing; cursing")
         ("Profound", "having deep meaning")
         ("Profundity", "depth")
         ("Prohibitive", "1. prohibiting; 2. exorbitantly expensive")
         ("Proletarian", "member of the working class")
         ("Proliferate", "grow and spread [proliferation (n)]")
         ("Prolific", "producing a lot")
         ("Prolixity", "wordiness [prolix (a)]")
         ("Prominent", "1. eminent; 2. protruding; 3. obvious")
         ("Prone", "1. vulnerable to; 2. horizontal")
         ("Propensity", "a natural inclination; tendency")
         ("Propitiate", "appease; try to gain favor [propitiation (n)]")
         ("Proponents", "promoters; supporters")
         ("Prosaic", "dull; boring; ordinary")
         ("Proscribe", "forbid")
         ("Prosody", "study of versification")
         ("Prostration", "1. lying face down; 2. be overcome with extreme weakness")
         ("Protagonist", "main character in film, book, play etc.")
         ("Protean", "changeable")
         ("Protocol", "procedure; code of behavior")
         ("Protract", "lengthen in time; cause to be or last longer")
         ("Protégé", "person under protection of, or guided by another")
         ("Provincial", "unsophisticated; narrow-minded")
         ("Proximate", "immediate; nearest")
         ("Prudence", "caution; wisdom")
         ("Prudent", "cautious; wise")
         ("Prudish",
          "narrow-minded; excessively concerned with morals [prudery (n), prude (n)]")
         ("Prune", "1. to trim; 2. a dried plum")
         ("Psychosis", "severe mental disturbance")
         ("Puerile", "childish")
         ("Pugnacious", "aggressive, ready to fight [pugnacity (n)]")
         ("Puissance", "power, might, or force")
         ("Punctilious", "paying attention to small details")
         ("Pundit", "expert")
         ("Purchase", "1. grip; 2. buy")
         ("Purist", "conservative; one who insists on correct forms of language etc.")
         ("Purloin", "steal")
         ("Purport", "have the often specious appearance of being or intending")
         ("Pusillanimous", "cowardly")
         ("Pyre", "ceremonial fire")
         ("Pyromania", "compulsion to start fires")
         ("Quack", "charlatan; fake")
         ("Quaff", "drink down quickly")
         ("Quagmire", "marsh; bog")
         ("Quaint", "picturesque")
         ("Qualm", "hesitation or fear")
         ("Quandary", "dilemma; puzzle")
         ("Quarantine", "isolation to prevent the spread of disease")
         ("Quarry", "1. something that is hunted; 2. mine for stone")
         ("Quell", "suppress")
         ("Querulous", "always complaining")
         ("Quibble",
          "1. (v) to argue about minor matters; to play on words when finding fault; 2. (n) a minor verbal point in an argument")
         ("Quintessential", "most typical; the perfect example of [quintessence (n)]")
         ("Quirk", "oddity")
         ("Quisling", "traitor")
         ("Quixotic", "impractically idealistic")
         ("Quotidian", "daily; routine")
         ("Raconteur", "person who relates a story")
         ("Ramble", "wander aimlessly")
         ("Ramifications", "branches; subdivisions of a complex system; outcomes")
         ("Rampart", "an embankment built around a space for defensive purposes")
         ("Rancor", "resentment; animosity; bad feeling")
         ("Rant", "use bombastic language")
         ("Rarefy", "make less dense [rarefaction (n)]")
         ("Ratify", "approve; consent")
         ("Raucous", "rough and unpleasant (of sounds)")
         ("Raven", "feed greedily")
         ("Raze", "destroy; demolish; tear down")
         ("Ready", "(used of wit) quick")
         ("Realm", "a domain in which something is dominant")
         ("Rebus", "puzzle in which pictures give clues")
         ("Rebuttal", "denial")
         ("Recant", "disclaim; retract statement")
         ("Recapitulate", "summarize")
         ("Receptacle", "container; vessel; holder")
         ("Recluse", "someone who cuts himself off from life")
         ("Recondite", "obscure; difficult to penetrate")
         ("Reconnaissance",
          "examination or survey conducted in advance [reconnoiter (v)]")
         ("Recumbent", "reclining; lying down")
         ("Recuperate", "get better after illness")
         ("Red", "tape	formalities; paperwork; official procedure")
         ("Redolent", "smelling of; giving off odors")
         ("Redress", "put right something that was wrong")
         ("Redundant", "unnecessary; superfluous")
         ("Referendum", "public vote")
         ("Refulgent", "glowing; radiant")
         ("Refute", "disprove")
         ("Regale", "entertain")
         ("Rekindle", "relight; revive")
         ("Relegate", "dismiss to a lower position")
         ("Remorse", "regret; sorrow; contrition")
         ("Remuneration", "payment for work done")
         ("Renege", "go back on promise or retract statement")
         ("Renown", "fame")
         ("Rent", "torn (past participle of the verb to rend)")
         ("Repine", "fret; be discontented")
         ("Replete", "full")
         ("Reprehensible", "shameful; very bad")
         ("Reprieve", "a respite; postponement of a sentence")
         ("Reprobate", "a person without moral scruples")
         ("Reproof", "scolding; criticism [reprove (v)]")
         ("Repudiate", "shun; eschew")
         ("Rescind", "retract; repeal")
         ("Resignation", "acceptance of fate")
         ("Resilience", "resistance; ability to spring back [resilience (a)]")
         ("Resolution", "determination")
         ("Resolve", "firmness (n)")
         ("Resonant", "echoing")
         ("Respite", "a pause from doing something; a break; intermission")
         ("Resplendent", "shining; glowing")
         ("Restorative", "a tonic")
         ("Resuscitation", "revival from unconsciousness [resuscitate (v)]")
         ("Retention", "preservation; withholding")
         ("Reticent", "restrained; holding something back; uncommunicative")
         ("Retraction", "withdrawal; cancellation of a statement")
         ("Revere", "worship")
         ("Riddled", "full of (usually full of holes)")
         ("Rife", "common")
         ("Rift", "a personal or social separation")
         ("Rigor", "thoroughness")
         ("Riveting",
          "fascinating [to rivet literally means to fix metal plates using metal pins]")
         ("Robust", "strong; healthy; tough")
         ("Roster", "list of names")
         ("Rotund", "round")
         ("Rue", "regret [rueful (a)]")
         ("Ruminate", "think over something; ponder")
         ("Runic", "mysterious; magical")
         ("Ruse", "trick; stratagem")
         ("Saccharin", "falsely sweet")
         ("Sacrosanct", "very holy; inviolable")
         ("Sagacious", "wise")
         ("Sage", "a wise person")
         ("Salacious", "lecherous; erotic")
         ("Sallow", "yellowish")
         ("Salubrious", "health-giving; promoting health")
         ("Salutary", "something which teaches you a lesson; beneficial")
         ("Sanctimonious", "hypocritically holy")
         ("Sanction", "give approval to")
         ("Sanguinary", "bloodthirsty; bloody")
         ("Sanguine", "optimistic; cheerful")
         ("Sap",
          "1. liquid inside plants (n); 2. to drain; to undermine (v); 3. a fool (n)")
         ("Sardonic", "mocking")
         ("Sate", "satisfy")
         ("Satiate", "satisfy; fill completely [satiable (a); satiation (n)]")
         ("Savant", "person with knowledge")
         ("Savor", "enjoy")
         ("Saw", "1. tool for cutting; 2. wise saying")
         ("Scabbard", "cover for a sword")
         ("Scale", "to climb")
         ("Scapegoat", "person on whom blame is placed for faults of others")
         ("Sceptic",
          "a person inclined to question or doubt accepted opinions.
          synonyms: cynic, doubter, questioner, scoffer")
         ("Schadenfreude", "pleasure derived by someone from another person's misfortune")
         ("Schism", "division of a group into opposing factions")
         ("Score", "(n) written form of music")
         ("Scotch", "(v)	to prevent; stop; disable")
         ("Scourge", "something causing misery or death")
         ("Scrupulous", "careful; diligent; painstaking")
         ("Scrutinize", "examine carefully")
         ("Scurvy", "1. disease due to lack of vitamin C; 2. contemptible; rascally")
         ("Scuttle", "sink")
         ("Secure", "(v) 1. to fix firmly; 2. to obtain")
         ("Sedulity", "thoroughness; perseverance [sedulous (a)]")
         ("Sedulous", "persevering; eager and thorough")
         ("Seemly", "appropriate (of behavior); decorous")
         ("Seine", "type of fishing net")
         ("Seminal", "essential; formative")
         ("Seminary", "an institution in which priests are trained")
         ("Sensuous", "appealing to the senses")
         ("Sentinel", "guard; sentry")
         ("Sequester", "isolate")
         ("Sere", "withered; old")
         ("Serendipity", "fortunate coincidence; unsought discovery")
         ("Serene", "calm; peaceful")
         ("Serrated", "jagged; saw-like")
         ("Servile", "overly submissive; groveling")
         ("Shard", "fragment of pottery")
         ("Shirk", "avoid (esp. work)")
         ("Sibyl", "prophetess")
         ("Sidereal", "of or related to stars")
         ("Sinecure", "job which pays salary but requiring little effort")
         ("Sinewy", "vigorous; having well-developed muscles [a sinew is a tendon]")
         ("Sinistral", "left-handed (or counterclockwise) [dextral - right handed]")
         ("Skeptical", "doubting; not gullible")
         ("Skiff", "small boat")
         ("Skirmish", "minor battle")
         ("Slake", "quench; satisfy")
         ("Slew", "glut; excess")
         ("Slight", "1. minor (a); 2. perceived insult (v) and (n)")
         ("Sluggard", "slow-moving; lethargic person")
         ("Smelt", "refine an ore")
         ("Smorgasbord", "a Swedish buffet of cold dishes")
         ("Sojourn", "a temporary stay")
         ("Solace", "comfort for grief")
         ("Solicit", "to ask for; seek")
         ("Solicitous", "kindly; expressing care and concern")
         ("Soliloquy", "solo speech")
         ("Somatic", "concerned with the body")
         ("Somnambulist", "sleepwalker")
         ("Soothsayer", "fortuneteller")
         ("Sophomoric", "juvenile; immature")
         ("Soporific", "inducing sleep")
         ("Sovereign", "a nation's ruler usually by hereditary right")
         ("Sparse", "spare; bare; meager")
         ("Specious", "false")
         ("Speckled", "spotted; freckled; dotted")
         ("Sporadic", "not continuous; intermittent")
         ("Spurious", "plausible but false")
         ("Squalid", "extremely dirty and unpleasant, especially as a result of poverty or neglect")
         ("Stagnant", "still; not moving")
         ("Staid", "dull; sober; serious")
         ("Stanch", "to stop something (especially blood) from flowing")
         ("Stanza", "section of a poem")
         ("Statute", "law [statutory (a)]")
         ("Staunch", "loyal; faithful; dependable")
         ("Steadfast", "marked by firm determination or resolution; not shakable")
         ("Steep", "(v)	to soak in water")
         ("Stereotype", "fixed image")
         ("Stevedore", "dockworker; longshoreman; dockers")
         ("Stickler", "one who is strict about rules or details")
         ("Stifle", "suppress")
         ("Stinting",
          "holding back; limiting the supply (of supplies/money etc.) [stint (v)]")
         ("Stipple", "cover with dots of paint etc.")
         ("Stipulate", "make an express demand or provision in an agreement")
         ("Stoic", "known for fortitude; indifferent to pleasure or pain")
         ("Stoke", "add fuel to; strengthen")
         ("Stolid", "impassive; dull; indifferent")
         ("Stomach", "(v) to tolerate")
         ("Stratagem", "plot; plan; trick")
         ("Strident", "unpleasantly loud and harsh")
         ("Stringent", "strict or severe")
         ("Strut",
          "1. supporting rod (n); 2. to walk in an arrogant manner; show off (v)")
         ("Stupefying", "astonishing; shocking; stunning into silence")
         ("Stygian", "very dark")
         ("Subliminal", "below the threshold of sensation or consciousness")
         ("Suborn", "bribe")
         ("Subpoena", "summons to court")
         ("Subsidiary", "functioning in a supporting capacity")
         ("Substantiate", "give supporting evidence")
         ("Subsume", "contain or include")
         ("Subterfuge", "a trick")
         ("Subtle", "not obvious")
         ("Subversive", "rebellious; revolutionary")
         ("Succinct", "concise")
         ("Suffragist", "someone who campaigns for voting rights")
         ("Sullied", "made dirty or impure [opposite unsullied; sully (v)]")
         ("Supercilious", "proud and haughty")
         ("Superlative", "extremely good; the best")
         ("Supine", "lying flat on one’s back")
         ("Supplicant", "person who requests or begs for something [supplicate (v)]")
         ("Surly", "grumpy; rude")
         ("Surreptitious", "secret; sneaky; stealthy")
         ("Susceptible", "vulnerable")
         ("Suspect", "doubtful")
         ("Sybarite", "lover of luxury")
         ("Sycophant", "bootlicker; flatterer")
         ("Syllogism", "reasoning in which a conclusion is derived from two premises")
         ("Symphony", "type of musical composition")
         ("Synapse", "junction between two nerve cells")
         ("Syncopation", "musical rhythm in which stress is given to the weak beats instead of the strong beats")
         ("Table", "(v)	put down for future discussion")
         ("Taciturn", "quiet; saying little")
         ("Tactile", "concerned with the sense of touch")
         ("Talisman", "lucky charm")
         ("Talon", "long pointed nail or claw")
         ("Tamp",
          "to plug; press loose matter down tightly (e.g. pack explosives into a hole)")
         ("Tangent", "going off the main subject")
         ("Tangible", "can be touched")
         ("Tardy", "slow; late; overdue; delayed")
         ("Tare", "1. weed; 2. allowance made for container when weighing")
         ("Tarnished", "made dull; spoil (reputation)")
         ("Taunt", "mock; tease")
         ("Tawdry", "of little value; gaudy")
         ("Tedium", "boredom")
         ("Teetotalism", "total abstinence from alcohol")
         ("Temper", "to moderate; soften")
         ("Temperate", "moderate")
         ("Tenacious", "stubborn; resolute; holding firm to a purpose")
         ("Tendentious", "dogmatic; biased")
         ("Tender", "to offer")
         ("Tentative", "not certain")
         ("Tenuous", "flimsy; not solid")
         ("Terse", "concise; to the point")
         ("Testiness", "irritability; irascibility [testy (a)]")
         ("Therapeutic", "medicinal; curative")
         ("Throwback", "exhibiting primitive, or ancestral, traits")
         ("Thwart", "prevent; frustrate")
         ("Timorous", "cowardly; fearful")
         ("Tirade", "stream of verbal abuse")
         ("Titter", "giggle quietly")
         ("Toady", "sycophant; flatterer")
         ("Tome", "large book")
         ("Torpid", "inactive; lazy; stagnant")
         ("Torpor", "dormancy; sluggishness; inactivity")
         ("Torrid", "hot and steamy")
         ("Tortuous", "indirect; winding")
         ("Totter", "walk unsteadily")
         ("Touting", "advertising; supporting [tout (v)]")
         ("Toy", "(v)	to play with")
         ("Tractable", "obedient; dutiful; polite")
         ("Tranquil", "peaceful")
         ("Transcendental",
          "supernatural; going beyond normal experience [transcendent (a)]")
         ("Transcribe", "copy")
         ("Transgress", "go astray; disobey; commit a sin")
         ("Transient", "short-lived; ephemeral")
         ("Traverse", "to move across")
         ("Travesty", "parody; ridiculous error")
         ("Trepidation", "fear")
         ("Trilogy", "set of three (literary works etc.); tetralogy = set of four")
         ("Trinket", "something of little value; knick-knack")
         ("Trite", "unoriginal; dull")
         ("Trivial", "unimportant")
         ("Truant", "shirker; someone absent without permission")
         ("Truculent", "eager or quick to argue or fight; aggressively defiant")
         ("Truncate", "cut short")
         ("Tumult", "uproar; noise")
         ("Turpitude", "")
         ("Tutelary", "serving as a guardian [tutelage (n)]")
         ("Tyro", "novice; beginner")
         ("Ubiquitous", "found everywhere; omnipresent")
         ("Umbrage", "1. shadow; 2. offense/offence; sense of injury")
         ("Unalloyed", "undiluted; total")
         ("Unctuous", "oily; using excessive flattery")
         ("Undercutting", "offering a lower price; undermining")
         ("Undergird",
          "to strengthen; secure, as by passing a rope or chain under and around")
         ("Undermine", "subvert; attempt to overthrow")
         ("Underscore", "emphasize")
         ("Underwrite", "give guarantee, insure")
         ("Unequivocal", "clear; obvious")
         ("Unfetter", "set free")
         ("Unfrock", "to remove a priest from his position")
         ("Unprecedented", "never having happened before")
         ("Unprepossessing", "unattractive")
         ("Unscathed", "unharmed; intact; without a scratch")
         ("Untoward", "unexpected")
         ("Unwitting", "not deliberate; unconscious")
         ("Upbraid", "scold; tell off; reprimand")
         ("Uproarious", "hilarious; hysterical; very funny")
         ("Upshot", "outcome")
         ("Urbane", "sophisticated; suave")
         ("Usurp", "take someone's position (usually by force)")
         ("Usury", "lending money at high interest rates")
         ("Utilitarian", "useful")
         ("Utopian", "a believer in an ideal world")
         ("Vacillate", "waver; hesitate")
         ("Vacuous", "empty; silly; meaningless")
         ("Vagary", "something unaccountable; freak")
         ("Vagrant", "person wandering without a home")
         ("Vapid", "dull; uninspiring")
         ("Variegated", "multicolored; speckled")
         ("Vehemence", "violence; fervor; forcefulness")
         ("Vehement", "forceful")
         ("Venal", "corrupt; can be bribed")
         ("Veneer", "surface coating")
         ("Venerate", "revere; worship")
         ("Veneration", "worship; respect [venerable (a), venerate (v)]")
         ("Venial", "minor; unimportant")
         ("Venturing",
          "1. hazarding; risking; putting forward; 2. going somewhere [venturesome means courageous or willing to take risks]")
         ("Veracious", "true [veracity (n)]")
         ("Veracity", "truthfulness")
         ("Verbiage", "excessive or meaningless wordiness")
         ("Verbose", "talkative; long-winded; rambling")
         ("Verbosity", "using too many words")
         ("Verisimilar", "having the appearance of truth; likely; probable")
         ("Verisimilitude", "the appearance of truth; the quality of seeming to be true")
         ("Veritable", "true; genuine [verity (n)]")
         ("Vertigo", "dizziness; a sensation of whirling and loss of balance, associated particularly with looking down from a great height, or caused by disease affecting the inner ear or the vestibular nerve; giddiness")
         ("Vestigial", "not developed")
         ("Vicissitude", "a change of circumstances or fortune, typically one that is unwelcome or unpleasant")
         ("Vignette", "small sketch")
         ("Vilification", "blackening someone's name")
         ("Vindicate", "prove right; remove blame")
         ("Virtuosity", "skill, expertise [virtuoso (n); virtuosi (n.pl)]")
         ("Virtuoso", "an accomplished musician")
         ("Virulent", "dangerous; harmful")
         ("Vital", "essential; alive; important")
         ("Vitiate", "weaken; sap energy")
         ("Vitriolic", "corrosive; strongly attacking")
         ("Vituperate", "attack bitterly")
         ("Vivacity", "liveliness; animation")
         ("Vivify", "enliven")
         ("Vociferous", "noisy; loud in speech")
         ("Volatile", "dangerously unstable; evaporates easily")
         ("Volubility", "excessive talkativeness [voluble (a)]")
         ("Voluble", "talkative")
         ("Voluminous", "very large; spacious")
         ("Voracious", "ravenous")
         ("Vulpine",
          "like a fox [compare with bovine (cow-like); porcine (pig-like), etc.]")
         ("Waffle", "talk nonsense")
         ("Waft", "drift smoothly (v); whiff; smell (n)")
         ("Wag", "(n)	a witty person")
         ("Waive", "surrender; give up")
         ("Wane", "grow less")
         ("Wary", "hesitant; cautious")
         ("Wax", "to increase; to grow")
         ("Waylay", "accost; stop; approach; hinder")
         ("Weighty", "serious")
         ("Whelp", "young dog")
         ("Whet", "sharpen")
         ("Whimsical", "capricious; changeable")
         ("Whittle", "1. carve with knife; 2. reduce step by step")
         ("Willful", "intentional; deliberate")
         ("Wily", "cunning")
         ("Wispy", "flimsy; frail; delicate")
         ("Wistful", "melancholy; pensive; expressing a longing for")
         ("Wry", "1. twisted or bent to one side; 2. dryly humorous")
         ("Xenophobe", "person afraid of foreigners")
         ("Zany", "crazy; wacky")
         ("Zeal", "enthusiasm")
         ("Zealot", "fanatic")
         ("Zenith", "summit")
         |]

    // let onlyWords = wordsAndMeaningsSorted |> Array.map fst
    // let checkForDuplicates = (Array.length onlyWords, set onlyWords |> Set.count)
