namespace Words
module WordsList =

    // let wordsAndMeanings =
    //     [|
    //      ("Abhor", "hate")
    //      ("Bigot", "narrow-minded, prejudiced person")
    //      ("Counterfeit", "fake; false")
    //      ("Enfranchise", "give voting rights")
    //      ("Hamper", "hinder; obstruct")
    //      ("Kindle", "to start a fire")
    //      ("Noxious", "harmful; poisonous; lethal")
    //      ("Placid", "calm; peaceful")
    //      ("Remuneration", "payment for work done")
    //      ("Talisman", "lucky charm")

    //      ("Abrasive", "rough; coarse; harsh")
    //      ("Bilk", "cheat; defraud")
    //      ("Covert", "hidden; undercover")
    //      ("Engender", "cause")
    //      ("Hangar", "storage area (like garage) for a plane")
    //      ("Knotty", "complex; difficult to solve")
    //      ("Nuance", "something subtle; a fine shade of meaning")
    //      ("Plagiarism", "taking credit for someone else's writing or ideas")
    //      ("Renown", "fame")
    //      ("Tangent", "going off the main subject")

    //      ("Abasement", "humiliation; degradation")
    //      ("Billowing", "swelling; fluttering; waving")
    //      ("Cower", "recoil in fear or servility; shrink away from")
    //      ("Enhance", "improve; make better or clearer")
    //      ("Harangue", "noisy, attacking speech")
    //      ("Labyrinth", "a maze")
    //      ("Nullify", "to counter; make unimportant")
    //      ("Plaintiff", "petitioner (in court of law)")
    //      ("Replete", "full")
    //      ("Tangible", "can be touched")

    //      ("Abrogate", "cancel; deny; repeal")
    //      ("Blasphemy", "speech which offends religious sentiments")
    //      ("Credible", "believable")
    //      ("Enigma", "puzzle; mystery")
    //      ("Harbingers", "indicators; bringers of warnings")
    //      ("Labyrinthine", "complicated; highly convoluted")
    //      ("Nuzzle", "cuddle; snuggle")
    //      ("Plaudit", "statement giving strong praise")
    //      ("Reprehensible", "shameful; very bad")
    //      ("Tardy", "slow; late; overdue; delayed")

    //      ("Absolution", "forgiveness; pardon; release")
    //      ("Blatant", "obvious")
    //      ("Creditable", "praiseworthy")
    //      ("Ensconce", "establish firmly in a position")
    //      ("Hasten", "hurry; accelerate; rush")
    //      ("Laceration", "a cut")
    //      ("Obdurate", "stubborn")
    //      ("Plausible", "can be believed; reasonable")
    //      ("Reprieve", "a respite; postponement of a sentence")
    //      ("Tawdry", "of little value; gaudy")

    //      ("Abstain", "desist; go without; withdraw")
    //      ("Blighted", "damaged; destroyed; ruined")
    //      ("Credulous", "gullible; ready to believe anything")
    //      ("Enshroud", "cover")
    //      ("Haughtiness", "arrogance; pride")
    //      ("Lachrymose", "tearful; sad")
    //      ("Obfuscate", "deliberately make something difficult to understand")
    //      ("Plethora", "an excess")
    //      ("Repudiate", "shun; eschew")
    //      ("Tedium", "boredom")

    //      ("Abstemious", "self denying; refraining from indulging")
    //      ("Blithe", "free-spirited; carefree")
    //      ("Crepuscular", "active at dawn and dusk")
    //      ("Enunciation", "clear pronunciation; accent; articulation")
    //      ("Headstrong", "stubborn; willful")
    //      ("Lackluster", "dull; monotonous; bland")
    //      ("Objective", "unbiased; not subjective")
    //      ("Pliable", "flexible; not stubborn")
    //      ("Rescind", "retract; repeal")
    //      ("Temper", "to moderate; soften")

    //      ("Abstruse", "difficult to understand; obscure")
    //      ("Blunderbuss", "1. ancient weapon (type of gun); 2. a clumsy person")
    //      ("Cringe", "recoil; flinch; shy away")
    //      ("Envenom", "to cause bitterness and bad feeling")
    //      ("Hedonism", "self indulgence; pleasure-seeking")
    //      ("Laconic", "using few words; brief; to the point")
    //      ("Oblique", "indirect; slanting")
    //      ("Plumage", "feathers of a bird")
    //      ("Resignation", "acceptance of fate")
    //      ("Tenacious", "stubborn; resolute; holding firm to a purpose")

    //      ("Accolade", "tribute; honor; praise")
    //      ("Bolster", "support; prop up")
    //      ("Cryptic", "puzzling; enigmatic")
    //      ("Ephemeral", "short-lived")
    //      ("Hedonist", "a pleasure seeker")
    //      ("Lamentation", "expression of regret or sorrow")
    //      ("Obliterate", "destroy; demolish; eradicate")
    //      ("Plummet", "fall suddenly and steeply")
    //      ("Resolution", "determination")
    //      ("Tentative", "not certain")

    //      ("Acquiesce", "to agree to; give in to")
    //      ("Bombast", "arrogant, pompous language")
    //      ("Curtail", "cut short")
    //      ("Epicure", "someone who appreciates good food and drink")
    //      ("Heed", "listen to")
    //      ("Lampoon", "ridicule; spoof")
    //      ("Oblivious", "totally unaware")
    //      ("Podium", "raised platform")
    //      ("Resonant", "echoing")
    //      ("Tenuous", "flimsy; not solid")

    //      ("Acrid", "sharp; pungent (used of smells and tastes)")
    //      ("Boorish", "ill-mannered")
    //      ("Cynical", "believing that people act only out of selfish motives")
    //      ("Epistle", "a letter (form of communication)")
    //      ("Heresy", "against orthodox opinion")
    //      ("Lance", "spear; spike; javelin")
    //      ("Obscure", "difficult to understand; partially hidden")
    //      ("Poignant", "deeply moving; strongly affecting the emotions")
    //      ("Respite", "a break; intermission")
    //      ("Terse", "concise; to the point")

    //      ("Acrophobia", "fear of heights")
    //      ("Bourgeois", "middle class")
    //      ("Debility", "weakness; incapacity")
    //      ("Epistolary", "concerned with letters; through correspondence")
    //      ("Hiatus", "interruption; pause")
    //      ("Languid", "tired; slow")
    //      ("Obscured", "hidden; covered; buried")
    //      ("Poised", "calm; collected; self-possessed")
    //      ("Resplendent", "shining; glowing")
    //      ("Therapeutic", "medicinal; curative")

    //      ("Acuity", "sharpness (mental or visual)")
    //      ("Braggart", "someone who boasts")
    //      ("Debunking", "exposing false claims or myths")
    //      ("Epitomized", "typified; characterized; personified")
    //      ("Hidebound", "rigid in opinions")
    //      ("Languish", "decay; fade away; get weaker")
    //      ("Obsequious", "servile; submissive")
    //      ("Polemical", "causing debate or argument")
    //      ("Restorative", "a tonic")
    //      ("Thwart", "prevent; frustrate")

    //      ("Adamant", "forceful; inflexible")
    //      ("Brawny", "muscular")
    //      ("Decathlon", "an athletic competition with ten events")
    //      ("Equivocate", "speak ambiguously; avoid telling the truth")
    //      ("Hieroglyphics", "1. picture writing; 2. writing which is difficult to read or enigmatic")
    //      ("Larceny", "theft; robbery; stealing")
    //      ("Obsession", "a dominating concern")
    //      ("Ponderous", "weighty; slow and heavy")
    //      ("Retention", "preservation; withholding")
    //      ("Timorous", "cowardly; fearful")

    //      ("Adroit", "skilful / skillful")
    //      ("Brevity", "being brief")
    //      ("Decorum", "dignified, correct behavior [decorous (a)]")
    //      ("Err", "make a mistake")
    //      ("Hinder", "obstruct")
    //      ("Largess", "generosity")
    //      ("Obsolete", "no longer valid")
    //      ("Pontificate", "speak pompously or dogmatically")
    //      ("Reticent", "restrained; holding something back; uncommunicative")
    //      ("Tirade", "stream of verbal abuse")

    //      ("Adulation", "strong admiration; worship")
    //      ("Bristle", "to show irritation")
    //      ("Decoy", "lure; trap; trick")
    //      ("Erratic", "wandering; irregular")
    //      ("Histrionic", "theatrical; exaggerated")
    //      ("Laud", "praise")
    //      ("Obstreperous", "noisy and boisterous")
    //      ("Portend", "foretell")
    //      ("Retraction", "withdrawal; cancellation of a statement")
    //      ("Titter", "giggle quietly")

    //      ("Adversity", "hardship")
    //      ("Broach", "start to discuss; approach")
    //      ("Deference", "respect")
    //      ("Esoteric", "obscure and difficult to understand")
    //      ("Hoary", "old")
    //      ("Lavish", "on a grand scale; wasteful")
    //      ("Obtuse", "mentally dull")
    //      ("Portent", "a warning sign; omen")
    //      ("Revere", "worship")
    //      ("Tome", "large book")

    //      ("Advocate", "support")
    //      ("Brusque", "blunt; abrupt")
    //      ("Defoliate", "cause leaves to fall off")
    //      ("Espouse", "promote; take up; support")
    //      ("Hone", "sharpen; increase; whet")
    //      ("Lax", "careless; not strict")
    //      ("Obviate", "avoid; make unnecessary")
    //      ("Poseur", "someone who puts on an act")
    //      ("Riddled", "full of (usually full of holes)")
    //      ("Torpid", "inactive; lazy; stagnant")

    //      ("Aesthetic", "concerning art or beauty")
    //      ("Bulwark", "fortification; barricade; wall")
    //      ("Defunct", "no longer in existence")
    //      ("Etymology", "the study of word origins")
    //      ("Hyperbole", "grossly exaggerated speech")
    //      ("Legend", "1. key to map; 2. myth or story")
    //      ("Odious", "hateful")
    //      ("Posterity", "future generations")
    //      ("Rife", "common")
    //      ("Torpor", "dormancy; sluggishness; inactivity")

    //      ("Affable", "friendly; social; easygoing")
    //      ("Bureaucracy", "officialdom")
    //      ("Degradation", "deprivation; poverty; debasement")
    //      ("Eulogy", "praise")
    //      ("Hypochondriac", "a person obsessed with health; having imaginary illnesses")
    //      ("Legion", "in large numbers")
    //      ("Officious", "domineering; intrusive; meddlesome")
    //      ("Posthumous", "after death")
    //      ("Rigor", "thoroughness")
    //      ("Totter", "walk unsteadily")

    //      ("Alacrity", "eagerness; enthusiasm; quickness")
    //      ("Burgeon", "grow; flourish; put forth new shoots")
    //      ("Deleterious", "harmful")
    //      ("Euphemism", "a polite phrase to cover something unpleasant")
    //      ("Hypocritical", "insincere")
    //      ("Lethargic", "tired; without energy")
    //      ("Ogle", "stare at; observe in an obvious manner")
    //      ("Postulate", "hypothesize; propose")
    //      ("Robust", "strong; healthy; tough")
    //      ("Tractable", "obedient; dutiful; polite")

    //      ("Alchemy", "medieval chemistry; attempt to change base metal into gold")
    //      ("Burnish", "polish")
    //      ("Deliberate", "to think over deeply")
    //      ("Euphony", "pleasant sounds")
    //      ("Iconoclast", "person who opposes orthodoxy")
    //      ("Levity", "flippancy; joking about serious matters")
    //      ("Olfactory", "concerned with the sense of smell")
    //      ("Potable", "suitable for drinking")
    //      ("Rotund", "round")
    //      ("Tranquil", "peaceful")

    //      ("Alibi", "an excuse that shows someone was not at a crime scene")
    //      ("Buttress", "strengthen; support")
    //      ("Delineation", "demarcation; explanation; definition; outlining")
    //      ("Evacuate", "vacate; empty; abandon")
    //      ("Idiosyncrasy", "a personal peculiarity; something unique to an individual")
    //      ("Libertarian", "someone who opposes tyranny")
    //      ("Ominous", "threatening")
    //      ("Potent", "powerful; compelling; strong")
    //      ("Ruminate", "think over something; ponder")
    //      ("Transcribe", "copy")

    //      ("Allay", "to lessen")
    //      ("Byline", "the line that tells you who wrote an article")
    //      ("Demur", "hesitate; refuse")
    //      ("Exacerbate", "make worse")
    //      ("Ignominious", "shameful")
    //      ("Liniment", "soothing lotion")
    //      ("Omnipotent", "all-powerful")
    //      ("Pragmatic", "practical")
    //      ("Ruse", "trick; stratagem")
    //      ("Transgress", "go astray; disobey; commit a sin")

    //      ("Alleviate", "make less severe")
    //      ("Cacophony", "discordant loud noises")
    //      ("Denounce", "condemn; speak out against")
    //      ("Exasperated", "frustrated; annoyed")
    //      ("Ignominy", "shame [ignominious (a) = shameful]")
    //      ("Lithe", "flexible; supple")
    //      ("Omniscient", "all-knowing")
    //      ("Pragmatist", "practical person; one who is concerned with usefulness")
    //      ("Saccharin", "falsely sweet")
    //      ("Transient", "short-lived; ephemeral")

    //      ("Aloof", "distant; detached; cold")
    //      ("Cajole", "coax")
    //      ("Deplete", "use up; lessen")
    //      ("Exceptionable", "very bad (something which we should object to)")
    //      ("Illuminate", "to light up or make clear")
    //      ("Livid", "very angry")
    //      ("Onerous", "burdensome; hard to undertake")
    //      ("Preamble", "introductory material")
    //      ("Sacrosanct", "very holy; inviolable")
    //      ("Traverse", "to move across")

    //      ("Altruism", "putting others first; being self-sacrificing")
    //      ("Caldron", "huge cooking pot")
    //      ("Deplore", "regret")
    //      ("Exculpate", "free someone from blame; pardon; acquit")
    //      ("Illusory", "deceptive; false; misleading")
    //      ("Lobbyist", "person who tries to persuade someone to support a particular cause")
    //      ("Onus", "burden")
    //      ("Precarious", "unstable; risky")
    //      ("Sagacious", "wise")
    //      ("Trepidation", "fear")

    //      ("Amass", "accumulate")
    //      ("Callow", "immature")
    //      ("Depravity", "moral corruption")
    //      ("Execrable", "very, very bad")
    //      ("Immoderate", "excessive; extreme")
    //      ("Lofty", "snooty; arrogant; haughty")
    //      ("Opaque", "does not let light through")
    //      ("Precedent", "a previous occurrence used as a guide")
    //      ("Sage", "a wise person")
    //      ("Trinket", "something of little value; knick-knack")

    //      ("Ambiguity", "uncertainty; vagueness")
    //      ("Candid", "frank; honest")
    //      ("Deprecate", "criticize; denounce")
    //      ("Exegesis", "scholarly explanation or interpretation")
    //      ("Immutable", "unchanging; permanent")
    //      ("Longevity", "long life")
    //      ("Opulent", "wealthy; rich; magnificent")
    //      ("Precept", "guiding principle")
    //      ("Salacious", "lecherous; erotic")
    //      ("Trite", "unoriginal; dull")

    //      ("Ambiguous", "unclear in meaning; can be interpreted in different ways")
    //      ("Candor", "frankness; openness")
    //      ("Deride", "ridicule; make fun of; mock")
    //      ("Exemplary", "outstandingly good; setting a fine example")
    //      ("Impartial", "unbiased; neutral")
    //      ("Loquacious", "talkative")
    //      ("Ordain", "1. destine; 2. confer holy orders on a priest")
    //      ("Precinct", "district of a city")
    //      ("Sallow", "yellowish")
    //      ("Trivial", "unimportant")

    //      ("Ambivalence", "lack of clarity; wavering; being undecided")
    //      ("Cantankerous", "bad-tempered; quarrelsome")
    //      ("Derogatory", "uncomplimentary")
    //      ("Exemplify", "to serve as a good example")
    //      ("Impecunious", "having no money")
    //      ("Lucid", "clear")
    //      ("Ornate", "highly decorated")
    //      ("Precipice", "steep slope")
    //      ("Salubrious", "health-giving")
    //      ("Truant", "shirker; someone absent without permission")

    //      ("Ambulatory", "able to walk around (used of hospital patients)")
    //      ("Capacious", "spacious")
    //      ("Desecrate", "to damage or pollute a holy place")
    //      ("Exhaustive", "complete and thorough")
    //      ("Impious", "wicked; profane")
    //      ("Ludicrous", "ridiculous; silly")
    //      ("Orthodox", "conventional")
    //      ("Precipitous", "done in a hurry")
    //      ("Salutary", "something which teaches you a lesson; beneficial")
    //      ("Truncate", "cut short")

    //      ("Ameliorate", "make better")
    //      ("Capitulate", "surrender; give in to")
    //      ("Desecration", "spoiling something holy")
    //      ("Exonerates", "acquits; absolves; removes blame")
    //      ("Impoverished", "destitute; poor")
    //      ("Lukewarm", "1. unenthusiastic; 2. neither hot nor cold")
    //      ("Ossify", "1. turn to bone; 2. become fixed and rigid")
    //      ("Preclude", "prevent or make impossible")
    //      ("Sanctimonious", "hypocritically holy")
    //      ("Tumult", "uproar; noise")

    //      ("Amelioration", "improvement")
    //      ("Carping", "constant criticism")
    //      ("Desist", "stop; discontinue; cease")
    //      ("Exorcism", "getting free/rid of; eliminating (especially demons)")
    //      ("Impromptu", "unrehearsed; spontaneous")
    //      ("Lummox", "clumsy person")
    //      ("Ostentatious", "showy")
    //      ("Precocious", "developing early")
    //      ("Sanction", "give approval to")
    //      ("Turpitude", "")

    //      ("Amiable", "friendly")
    //      ("Cartographer", "person who makes maps")
    //      ("Despondent", "having no hope; miserable")
    //      ("Expatriate", "refugee; emigrant; someone living away from his own country")
    //      ("Inadvertent", "not intentional")
    //      ("Luscious", "juicy; moist; succulent")
    //      ("Oust", "push out of a position")
    //      ("Predecessor", "one who came before")
    //      ("Sanguinary", "bloodthirsty; bloody")
    //      ("Tyro", "novice; beginner")

    //      ("Amity", "friendship")
    //      ("Castigate", "scold strongly")
    //      ("Destitution", "hardship; poverty; misery")
    //      ("Expedient", "convenient; practical")
    //      ("Incantation", "chant; invocation; prayer")
    //      ("Lynch", "assassinate; kill; illegal hanging")
    //      ("Overt", "obvious; not hidden")
    //      ("Predicament", "dilemma; difficult situation")
    //      ("Sanguine", "optimistic; cheerful")
    //      ("Ubiquitous", "found everywhere; omnipresent")

    //      ("Amorphous", "lacking in shape")
    //      ("Catharsis", "purging of pent-up emotions")
    //      ("Deter", "put off; prevent")
    //      ("Expedite", "make faster")
    //      ("Incarceration", "putting in prison")
    //      ("Machinations", "plots and plans")
    //      ("Overwrought", "worked up; in an emotional state")
    //      ("Preeminent", "famous; outstanding")
    //      ("Sardonic", "mocking")
    //      ("Unalloyed", "undiluted; total")

    //      ("Analgesic", "medicine to combat pain")
    //      ("Caucus", "type of private political meeting")
    //      ("Deteriorate", "worsen; decline")
    //      ("Exposition", "clear explanation")
    //      ("Incessant", "without stopping")
    //      ("Maelstrom", "whirlpool; storm in the ocean")
    //      ("Palatable", "good to eat; agreeable")
    //      ("Prerogative", "right or privilege")
    //      ("Savant", "person with knowledge")
    //      ("Unctuous", "oily; using excessive flattery")

    //      ("Analogous", "comparable")
    //      ("Caustic", "burning")
    //      ("Detrimental", "harmful")
    //      ("Extol", "praise")
    //      ("Incipient", "just beginning")
    //      ("Magnanimous", "generous; big-hearted")
    //      ("Palisade", "fence made of posts")
    //      ("Prescient", "having fore-knowledge")
    //      ("Scale", "to climb")
    //      ("Undermined", "damaged; attacked")

    //      ("Anarchy", "chaos; lack of government")
    //      ("Cavalcade", "procession of vehicles")
    //      ("Devoured", "greedily eaten/consumed")
    //      ("Extradite", "deport from one country back to the home country")
    //      ("Inclination", "tendency; a leaning toward")
    //      ("Magnate", "powerful businessman")
    //      ("Palliative", "a remedy that improves but doesn't cure")
    //      ("Presentiment", "a feeling that something might happen")
    //      ("Scapegoat", "person on whom blame is placed for faults of others")
    //      ("Underscore", "emphasize")

    //      ("Anecdote", "a brief amusing story")
    //      ("Celerity", "speed")
    //      ("Dexterous", "skilful with hands")
    //      ("Extraneous", "irrelevant")
    //      ("Incoherent", "not clear")
    //      ("Maladroit", "clumsy; unskillful")
    //      ("Pallid", "pale")
    //      ("Presumptuous", "assuming too much; arrogant")
    //      ("Scrupulous", "careful; diligent; painstaking")
    //      ("Unequivocal", "clear; obvious")

    //      ("Animosity", "hatred; antagonism")
    //      ("Censorious", "disapproving; critical")
    //      ("Dichotomy", "a division into two parts")
    //      ("Extrapolate", "extend; predict on the basis of known data")
    //      ("Incongruous", "not fitting in; out of place")
    //      ("Malady", "illness")
    //      ("Palpable", "easily felt; easily perceived")
    //      ("Pretentious", "pompous; self-important")
    //      ("Scrutinize", "examine carefully")
    //      ("Unfetter", "set free")

    //      ("Annex", "(n)	a building which is an addition to an existing building")
    //      ("Censure", "blame")
    //      ("Didactic", "intended to teach; instructive")
    //      ("Extrinsic", "irrelevant; on the outside")
    //      ("Inconsequential", "unimportant; insignificant; negligible")
    //      ("Malediction", "a curse")
    //      ("Panacea", "remedy for all ills")
    //      ("Prevaricate", "speak misleadingly and evasively")
    //      ("Scuttle", "sink")
    //      ("Unfrock", "to remove a priest from his position")

    //      ("Annex", "(v)	take possession of; seize; capture")
    //      ("Cerebral", "intellectual")
    //      ("Diffident", "lacking confidence")
    //      ("Fallacious", "false")
    //      ("Inconspicuous", "not easily seen; subtle; not noticeable")
    //      ("Malefactor", "a wrong-doer")
    //      ("Paradigm", "1. example; 2. model; 3. way of looking at things")
    //      ("Pristine", "unspoiled")
    //      ("Seminary", "an institution in which priests are trained")
    //      ("Unprecedented", "never having happened before")

    //      ("Anomaly", "something which does not fit in a pattern; irregularity")
    //      ("Certitude", "certainty")
    //      ("Digress", "wander off the subject")
    //      ("Falter", "hesitate; waver")
    //      ("Indelible", "cannot be wiped out")
    //      ("Malinger", "deliberately avoid work; shirk")
    //      ("Paradox", "apparently contradictory statement")
    //      ("Proclivity", "tendency towards")
    //      ("Sensuous", "appealing to the senses")
    //      ("Unscathed", "unharmed; intact; without a scratch")

    //      ("Antagonism", "hostility; strong opposition")
    //      ("Charlatan", "trickster who claims knowledge he doesn't have")
    //      ("Dike", "dam; embankment")
    //      ("Fanatical", "obsessive; fixated")
    //      ("Indifferent", "1. neutral; 2. not outstanding")
    //      ("Malingerer", "person who deliberately tries to avoid work")
    //      ("Paragon", "a perfect example")
    //      ("Procrastinate", "delay; put off")
    //      ("Sentinel", "guard; sentry")
    //      ("Unwitting", "not deliberate; unconscious")

    //      ("Antagonistic", "opposed; hostile; aggressive")
    //      ("Chary", "wary of; cautious about; reluctant to give")
    //      ("Dilatory", "slow; falling behind with one's work")
    //      ("Fanaticism", "passion; excessive devotion")
    //      ("Indigenous", "native to a particular area")
    //      ("Malleable", "flexible; can be shaped")
    //      ("Paramount", "of supreme importance")
    //      ("Prodigal", "wasteful; extravagant")
    //      ("Sequester", "isolate")
    //      ("Upbraid", "scold; tell off; reprimand")

    //      ("Antediluvian", "outdated; prehistoric; very old-fashioned")
    //      ("Chastises", "punishes")
    //      ("Dilemma", "puzzling situation")
    //      ("Fastidious", "overly particular; finicky")
    //      ("Indolence", "laziness")
    //      ("Mallet", "1. wooden hammer; 2. stick used for polo")
    //      ("Parasite", "1. scrounger; 2. animal which takes digested food from another")
    //      ("Prodigious", "very large")
    //      ("Serendipity", "fortunate coincidence; unsought discovery")
    //      ("Uproarious", "hilarious; hysterical; very funny")

    //      ("Anthology", "a book which is a collection of poems or stories")
    //      ("Chicanery", "trickery")
    //      ("Dilettante", "person who dabbles in a subject without serious study")
    //      ("Fatuous", "silly; foolish")
    //      ("Inductee", "novice; beginner")
    //      ("Manipulatable", "influencable; controllable")
    //      ("Parched", "dried up")
    //      ("Profane", "unholy")
    //      ("Serene", "calm; peaceful")
    //      ("Upshot", "outcome")

    //      ("Anthropocentrism", "putting man at the center of one's philosophy")
    //      ("Chimerical", "changeable; unstable")
    //      ("Diligent", "hard-working")
    //      ("Feasible", "possible and practicable")
    //      ("Indulgent", "pampering; satisfying desires")
    //      ("Marred", "damaged; spoiled")
    //      ("Pariah", "an outcast from society")
    //      ("Profanity", "swearing; cursing")
    //      ("Serrated", "jagged; saw-like")
    //      ("Urbane", "sophisticated; suave")

    //      ("Antiquated", "outdated; old fashioned")
    //      ("Choleric", "easily angered")
    //      ("Diorama", "model of a scene")
    //      ("Fecund", "fertile")
    //      ("Inebriation", "drunkenness; intoxication")
    //      ("Marshal", "to gather together")
    //      ("Parity", "equality")
    //      ("Profound", "having deep meaning")
    //      ("Servile", "overly submissive; groveling")
    //      ("Usurp", "take someone's position (usually by force)")

    //      ("Apathetic", "indifferent; uninterested; lethargic")
    //      ("Chronicler", "person who records historical information")
    //      ("Dirge", "mournful song")
    //      ("Felicitous", "apt, well-suited for the occasion")
    //      ("Ineffable", "cannot be expressed in words")
    //      ("Marsupial", "pouched mammal (like a kangaroo)")
    //      ("Parochial", "narrow-minded; concerned only with local matters")
    //      ("Profundity", "depth")
    //      ("Skeptical", "doubting; not gullible")
    //      ("Utilitarian", "useful")

    //      ("Apathy", "lack of interest or emotion")
    //      ("Circuitous", "indirect")
    //      ("Disapprobation", "disapproval")
    //      ("Fervor", "passion; enthusiasm")
    //      ("Inept", "incompetent; unskilled; useless")
    //      ("Martinet", "person who believes in strict discipline")
    //      ("Parody", "a mockery; imitation for ridicule; spoof")
    //      ("Proletarian", "member of the working class")
    //      ("Skirmish", "minor battle")
    //      ("Utopian", "a believer in an ideal world")

    //      ("Apocryphal", "of doubtful origin")
    //      ("Circumlocution", "using too many words; long-windedness")
    //      ("Discern", "to distinguish one thing from another")
    //      ("Fickle", "unpredictable; whimsical; easily swayed")
    //      ("Inertia", "inactivity; lethargy")
    //      ("Masochist", "person who intentionally inflicts pain on himself")
    //      ("Parry", "ward off; avoid")
    //      ("Prolific", "producing a lot")
    //      ("Sluggard", "slow-moving; lethargic person")
    //      ("Vacillate", "waver; hesitate")

    //      ("Appease", "pacify; soothe; calm down; make peace with")
    //      ("Circumscribe", "limit")
    //      ("Discord", "disagreement")
    //      ("Finesse", "skill")
    //      ("Inevitable", "cannot be avoided")
    //      ("Matriarchy", "society governed by women")
    //      ("Parsimonious", "economical; frugal; thrifty")
    //      ("Proponents", "promoters; supporters")
    //      ("Smelt", "refine an ore")
    //      ("Vacuous", "empty; silly; meaningless")

    //      ("Apprehensive", "worried; fearful")
    //      ("Circumspect", "cautious; considering all sides")
    //      ("Discordancy", "cacophony; harshness; jarring")
    //      ("Fitful", "not continuous; stopping and starting")
    //      ("Inexorable", "relentless")
    //      ("Maverick", "a loner")
    //      ("Parsimony", "stinginess; frugality; cost-cutting")
    //      ("Prosaic", "dull; boring; ordinary")
    //      ("Smorgasbord", "a Swedish buffet of cold dishes")
    //      ("Vagrant", "person wandering without a home")

    //      ("Arable", "can be cultivated")
    //      ("Circumvent", "avoid")
    //      ("Discrepancy", "something which does not match up; inconsistency")
    //      ("Flagrant", "clearly wrong")
    //      ("Inexpedient", "not advisable")
    //      ("Meager", "in short supply")
    //      ("Partisan", "biased; one-sided; committed to one group")
    //      ("Proscribe", "forbid")
    //      ("Solace", "comfort for grief")
    //      ("Vapid", "dull; uninspiring")

    //      ("Arbitrary", "random; for no definite reason")
    //      ("Clairvoyant", "psychic; mystic")
    //      ("Discriminate", "to make a clear distinction; see the difference")
    //      ("Flamboyant", "showy; ornate")
    //      ("Infallible", "perfect; flawless; cannot make mistakes")
    //      ("Meander", "wander from side to side")
    //      ("Pathos", "evoking sadness or pity")
    //      ("Prosody", "study of versification")
    //      ("Solicit", "to ask for; seek")
    //      ("Variegated", "multicolored; speckled")

    //      ("Arcane", "obscure; known only to a few people")
    //      ("Clamor", "shout; scream")
    //      ("Discursiveness", "long windedness; indirectness")
    //      ("Flaunt", "show off; display in a showy manner")
    //      ("Infamous", "famous for something bad")
    //      ("Mellow", "soft; melodious; ripe")
    //      ("Patron", "one who give support (usually financial)")
    //      ("Prostration", "1. lying face down; 2. be overcome with extreme weakness")
    //      ("Somnambulist", "sleepwalker")
    //      ("Vehemence", "violence; fervor; forcefulness")

    //      ("Archaic", "ancient; outdated; old fashioned")
    //      ("Clandestine", "secret; covert; stealthy")
    //      ("Disdain", "contempt; strong dislike")
    //      ("Flippant", "making jokes about serious matters")
    //      ("Infer", "deduce; conclude")
    //      ("Menagerie", "collection of animals")
    //      ("Patronize", "condescend to; behave in an arrogant manner towards")
    //      ("Protagonist", "main character in film, book, play etc.")
    //      ("Soothsayer", "fortuneteller")
    //      ("Vehement", "forceful")

    //      ("Archetype", "classic example of")
    //      ("Clemency", "mercy")
    //      ("Disinterested", "unbiased")
    //      ("Flout", "defy; reject")
    //      ("Ingénue", "naïve, unsophisticated person")
    //      ("Mendacious", "given to lying")
    //      ("Paucity", "shortage")
    //      ("Protean", "changeable")
    //      ("Sophomoric", "juvenile; immature")
    //      ("Venal", "corrupt; can be bribed")

    //      ("Archives", "collections of old records; place of storage of old documents")
    //      ("Cliché", "overused expression; something unoriginal")
    //      ("Disparage", "criticize; belittle")
    //      ("Flustered", "worked-up; not calm")
    //      ("Ingrate", "ungrateful person")
    //      ("Mercenary", "concerned only with money")
    //      ("Peccadillo", "minor weakness; trivial offence")
    //      ("Protégé", "person under protection of, or guided by another")
    //      ("Soporific", "inducing sleep")
    //      ("Veneer", "surface coating")

    //      ("Articulate", "clear; lucid; eloquent")
    //      ("Clientele", "customers")
    //      ("Disparity", "an inequality")
    //      ("Fly-by-night", "unreliable; disreputable")
    //      ("Inimical", "hostile")
    //      ("Mercurial", "volatile; changeable")
    //      ("Pedant", "person who insists on strict adherence to rules or narrow learning")
    //      ("Protocol", "procedure; code of behavior")
    //      ("Sparse", "spare; bare; meager")
    //      ("Venerate", "revere; worship")

    //      ("Artifice", "deception; trickery")
    //      ("Coalesce", "come together; merge")
    //      ("Dispassionate", "neutral; objective")
    //      ("Forensic", "concerned with argument or debate (esp. for legal evidence)")
    //      ("Innate", "inherited; inborn")
    //      ("Merge", "come together")
    //      ("Pedestrian", "common; mundane; banal")
    //      ("Provincial", "unsophisticated; narrow-minded")
    //      ("Specious", "false")
    //      ("Venial", "minor; unimportant")

    //      ("Artisan", "craftsman")
    //      ("Coddle", "pamper; fuss over; indulge")
    //      ("Disseminating", "circulating; broadcasting; spreading (information)")
    //      ("Fortitude", "bravery")
    //      ("Innocuous", "harmless; inoffensive")
    //      ("Metaphorically", "symbolically; figuratively")
    //      ("Peerless", "without equal")
    //      ("Prudent", "cautious; wise")
    //      ("Speckled", "spotted; freckled; dotted")
    //      ("Veracity", "truthfulness")

    //      ("Ascetic", "without luxuries; severely simple")
    //      ("Coercion", "force")
    //      ("Diurnal", "active in daytime")
    //      ("Fortuitous", "happening by chance")
    //      ("Innovate", "create; introduce something new")
    //      ("Meticulous", "very careful; painstaking")
    //      ("Pejorative", "derogatory")
    //      ("Puerile", "childish")
    //      ("Sporadic", "not continuous; intermittent")
    //      ("Verbose", "talkative; long-winded; rambling")

    //      ("Assiduous", "thorough; diligent")
    //      ("Cogent", "lucid; well argued")
    //      ("Divert", "1. entertain; 2. distract; 3. cause a detour")
    //      ("Fractious", "irritable; difficult to control")
    //      ("Inscrutable", "mysterious; impenetrable")
    //      ("Mettle", "courage; bravery; valor")
    //      ("Pellucid", "transparently clear")
    //      ("Punctilious", "paying attention to small details")
    //      ("Spurious", "false")
    //      ("Verbosity", "using too many words")

    //      ("Assuage", "to calm")
    //      ("Cogitate", "think over something; ponder")
    //      ("Docile", "gentle and easily lead")
    //      ("Fraudulent", "fake; false")
    //      ("Insentient", "unfeeling")
    //      ("Milieu", "environment")
    //      ("Pensive", "in a thoughtful mood; thinking deeply")
    //      ("Purloin", "steal")
    //      ("Stagnant", "still; not moving")
    //      ("Vertigo", "dizziness")

    //      ("Astute", "perceptive; sharp-witted")
    //      ("Collage", "picture made from fragments of other pictures")
    //      ("Dogmatic", "having stubbornly held opinions")
    //      ("Frivolous", "not serious")
    //      ("Insipid", "dull; bland; boring")
    //      ("Mire", "swamp; muddy ground")
    //      ("Penury", "poverty")
    //      ("Pusillanimous", "cowardly")
    //      ("Staid", "dull; sober; serious")
    //      ("Vestigial", "not developed")

    //      ("Asylum", "place of refuge or safety")
    //      ("Collate", "arrange in order")
    //      ("Dolt", "stupid person")
    //      ("Frugal", "economical; not wasting anything")
    //      ("Instigate", "to start; provoke")
    //      ("Misanthrope", "hater of the rest of mankind")
    //      ("Perceptive", "observant")
    //      ("Pyromania", "compulsion to start fires")
    //      ("Stanza", "section of a poem")
    //      ("Vignette", "small sketch")

    //      ("Atheist", "person who does not believe in God")
    //      ("Colloquial", "local and informal (used of language)")
    //      ("Dotard", "foolish old man")
    //      ("Furrow", "groove")
    //      ("Instigator", "troublemaker; person who entices others to do something")
    //      ("Misnomer", "wrong name")
    //      ("Percipient", "perceptive; insightful")
    //      ("Quaff", "drink down quickly")
    //      ("Staunch", "loyal; faithful; dependable")
    //      ("Vilification", "blackening someone's name")

    //      ("Atrophy", "waste away from lack of use")
    //      ("Collusion", "plotting and planning")
    //      ("Drawl", "speak slowly with words running together")
    //      ("Furtive", "hidden and secret")
    //      ("Insurgent", "a rebel")
    //      ("Misogynist", "hater of women")
    //      ("Perdition", "damnation")
    //      ("Quagmire", "marsh; bog")
    //      ("Stereotype", "fixed image")
    //      ("Vindicate", "prove right; remove blame")

    //      ("Attenuate", "weaken")
    //      ("Commandeer", "take possession of")
    //      ("Drivel", "nonsense")
    //      ("Futile", "useless; hopeless")
    //      ("Interminable", "never-ending")
    //      ("Misrepresentation", "deliberately deceiving")
    //      ("Peremptory", "in a commanding manner")
    //      ("Quaint", "picturesque")
    //      ("Stevedore", "dockworker")
    //      ("Virtuoso", "an accomplished musician")

    //      ("Augment", "increase; make bigger")
    //      ("Complacent", "self-satisfied; smug")
    //      ("Droll", "dryly amusing")
    //      ("Galleon", "ancient type of sailing ship")
    //      ("Intermittent", "sporadic; irregular")
    //      ("Mitigate", "lessen; make less severe")
    //      ("Perfidy", "treachery")
    //      ("Quandary", "dilemma; puzzle")
    //      ("Stifle", "suppress")
    //      ("Virulent", "dangerous; harmful")

    //      ("Auspicious", "favorable; promising to turn out well")
    //      ("Compliant", "easy to control; submissive")
    //      ("Drone", "1. monotonous noise (n); 2. to speak with no emotion (v); 3.male bee")
    //      ("Gambol", "frolic; leap; bound")
    //      ("Intransigence", "stubbornness")
    //      ("Modicum", "small amount")
    //      ("Perfunctory", "superficial; cursory")
    //      ("Quarantine", "isolation to prevent the spread of disease")
    //      ("Stoic", "known for fortitude; indifferent to pleasure or pain")
    //      ("Vital", "essential; alive; important")

    //      ("Austere", "severely plain")
    //      ("Concatenate", "link together")
    //      ("Dubious", "doubtful")
    //      ("Garble", "distort; confuse; muddle")
    //      ("Intransigent", "stubborn; unyielding")
    //      ("Momentous", "very important")
    //      ("Peripatetic", "nomadic; moving from place to place")
    //      ("Quarry", "1. something that is hunted; 2. mine for stone")
    //      ("Stoke", "add fuel to; strengthen")
    //      ("Vitriolic", "corrosive; strongly attacking")

    //      ("Aversion", "a dislike of")
    //      ("Concatenation", "linking into chains")
    //      ("Dupe", "to fool someone")
    //      ("Garish", "gaudy")
    //      ("Intrepid", "brave")
    //      ("Monotonous", "dull; unvarying")
    //      ("Peripheral", "on the edge; not important")
    //      ("Querulous", "always complaining")
    //      ("Stolid", "impassive; dull; indifferent")
    //      ("Vivacity", "liveliness; animation")

    //      ("Balk", "hinder and prevent; hesitate over")
    //      ("Conciliate", "to bring together; end a dispute")
    //      ("Dynamic", "lively; vibrant; energetic")
    //      ("Garner", "gather; collect")
    //      ("Inveterate", "habitual")
    //      ("Moratorium", "temporary prohibition or halt to activity")
    //      ("Perjury", "telling lies under oath")
    //      ("Quirk", "oddity")
    //      ("Stratagem", "plot; plan; trick")
    //      ("Vivify", "enliven")

    //      ("Banal", "common; dull")
    //      ("Concise", "stated in few words")
    //      ("Ebullient", "very lively; cheerful; jovial; happy")
    //      ("Garrulous", "talkative")
    //      ("Invidious", "arousing envy")
    //      ("Moribund", "on the point of death")
    //      ("Pernicious", "destructive; harmful")
    //      ("Ramble", "wander aimlessly")
    //      ("Strident", "loud and harsh")
    //      ("Vociferous", "noisy; loud in speech")

    //      ("Banality", "ordinariness; dullness")
    //      ("Condescend", "talk down to")
    //      ("Eccentric", "unusual; quirky; odd")
    //      ("Gaunt", "emaciated; bony and angular")
    //      ("Inviolable", "cannot be invaded")
    //      ("Morose", "gloomy; bad tempered")
    //      ("Persnickety", "fastidious; fussy")
    //      ("Ramifications", "branches; subdivisions of a complex system; outcomes")
    //      ("Stringent", "strict or severe")
    //      ("Volatile", "dangerously unstable; evaporates easily")

    //      ("Bane", "troublesome influence")
    //      ("Condone", "tacitly support; overlook")
    //      ("Eclectic", "taking things from different sources")
    //      ("Genre", "a category; type")
    //      ("Irascible", "easily angered")
    //      ("Mundane", "ordinary; worldly")
    //      ("Perpetuated", "caused to continue")
    //      ("Rancor", "resentment; animosity; bad feeling")
    //      ("Strut", "swagger; show off")
    //      ("Voluble", "talkative")

    //      ("Bard", "poet")
    //      ("Condoning", "overlooking; disregarding; ignoring")
    //      ("Edifice", "building; structure; construction")
    //      ("Germane", "relevant")
    //      ("Ire", "anger [irate (a) = very angry]")
    //      ("Munificent", "generous; charitable")
    //      ("Perpetuity", "eternity")
    //      ("Rant", "use bombastic language")
    //      ("Stupefying", "astonishing; shocking; stunning into silence")
    //      ("Voluminous", "very large; spacious")

    //      ("Bastion", "fortress; stronghold")
    //      ("Conflagration", "big fire")
    //      ("Efface", "wipe out; remove all trace of")
    //      ("Germinal", "just growing; not developed; immature")
    //      ("Irksome", "annoying; infuriating")
    //      ("Mutinous", "very rebellious")
    //      ("Personable", "attractive")
    //      ("Ratify", "approve; consent")
    //      ("Subpoena", "summons to court")
    //      ("Voracious", "ravenous")

    //      ("Befuddle", "confuse")
    //      ("Confound", "confuse")
    //      ("Effigy", "a model of a person")
    //      ("Gibbering", "making meaningless noises")
    //      ("Ironic", "satiric; unexpected")
    //      ("Myriad", "in large numbers")
    //      ("Perspicacious", "insightful; sharp; wise")
    //      ("Raucous", "rough and unpleasant (of sounds)")
    //      ("Substantiate", "give supporting evidence")
    //      ("Waive", "surrender; give up")

    //      ("Begrudge", "resent")
    //      ("Congeal", "to solidify")
    //      ("Effusive", "gushing; demonstrative")
    //      ("Glacial", "hostile; unfriendly; cold; icy")
    //      ("Irrational", "unreasonable; absurd")
    //      ("Navigable", "suitable for sailing")
    //      ("Perspicacity", "insight")
    //      ("Raze", "destroy; demolish; tear down")
    //      ("Subterfuge", "a trick")
    //      ("Wane", "grow less")

    //      ("Beguile", "mislead; lure")
    //      ("Congenital", "present from birth")
    //      ("Egalitarianism", "belief in equality")
    //      ("Goad", "prod; urge")
    //      ("Irreproachable", "cannot be criticized; perfect")
    //      ("Nebulous", "vague")
    //      ("Pertinent", "relevant")
    //      ("Rebuttal", "denial")
    //      ("Subtle", "not obvious")
    //      ("Wary", "hesitant; cautious")

    //      ("Belabor", "explain in unnecessary detail")
    //      ("Connoisseur", "person with refined taste and good judgment")
    //      ("Egregious", "outstandingly, obviously bad")
    //      ("Grate", "(v)	1. to annoy; aggravate; vex; 2. shred")
    //      ("Irrevocable", "cannot be cancelled; unchangeable")
    //      ("Nefarious", "wicked; immoral; disreputable")
    //      ("Peruse", "read carefully")
    //      ("Recant", "disclaim; retract statement")
    //      ("Subversive", "rebellious; revolutionary")
    //      ("Wax", "to increase; to grow")

    //      ("Beleaguer", "besiege; attack")
    //      ("Consecrate", "dedicate")
    //      ("Egress", "exit")
    //      ("Gratis", "free of charge; without payment")
    //      ("Itinerant", "nomadic; wandering from place to place")
    //      ("Negate", "cancel; deny")
    //      ("Pervasive", "spreading everywhere")
    //      ("Recapitulate", "summarize")
    //      ("Succinct", "concise")
    //      ("Waylay", "accost; stop; approach; hinder")

    //      ("Belie", "contradict")
    //      ("Consensus", "general agreement")
    //      ("Eloquent", "fluent and persuasive in speech")
    //      ("Gratuitous", "unwarranted")
    //      ("Jaded", "tired; bored; worn out")
    //      ("Negligence", "carelessness")
    //      ("Petrify", "1. terrify; 2. turn to stone")
    //      ("Receptacle", "container; vessel; holder")
    //      ("Suffragist", "someone who campaigns for voting rights")
    //      ("Weighty", "serious")

    //      ("Belittle", "to demean")
    //      ("Conspicuous", "easily seen; prominent")
    //      ("Elucidate", "make clear")
    //      ("Gravity", "seriousness")
    //      ("Jargon", "specialized language used by experts")
    //      ("Neologism", "newly coined word")
    //      ("Petulant", "sulky; peevish")
    //      ("Recluse", "someone who cuts himself off from life")
    //      ("Supercilious", "proud and haughty")
    //      ("Whelp", "young dog")

    //      ("Bellicose", "war-like; aggressive")
    //      ("Consummate", "complete; total; supremely good")
    //      ("Elusive", "hard to pin down")
    //      ("Gregarious", "extroverted; sociable; outgoing")
    //      ("Jaundiced", "cynical; pessimistic")
    //      ("Nettle", "annoy")
    //      ("Phenomenon", "an event or happening (plural: phenomena)")
    //      ("Recuperate", "get better after illness")
    //      ("Superlative", "extremely good; the best")
    //      ("Whet", "sharpen")

    //      ("Belligerent", "aggressive; ready to fight")
    //      ("Contemporary", "living or happening at the same time")
    //      ("Emaciated", "very thin; withered")
    //      ("Gritty", "coarse; granular")
    //      ("Jaunt", "short pleasure trip")
    //      ("Niggardly", "miserly; stingy")
    //      ("Philanthropy", "charity; love of mankind")
    //      ("Red", "tape	formalities; paperwork; official procedure")
    //      ("Surly", "grumpy; rude")
    //      ("Whimsical", "capricious; changeable")

    //      ("Bemoan", "complain about")
    //      ("Contrite", "sorry")
    //      ("Emancipate", "set free")
    //      ("Guffaw", "sudden loud laughter")
    //      ("Jeopardize", "put at risk; endanger")
    //      ("Nomadic", "wandering from place to place")
    //      ("Philistine", "uncultured person")
    //      ("Redolent", "smelling of; giving off odors")
    //      ("Surreptitious", "secret; sneaky; stealthy")
    //      ("Willful", "stubborn")

    //      ("Benevolent", "kindly")
    //      ("Contrition", "sorrow and repentance")
    //      ("Embezzle", "defraud; steal")
    //      ("Guile", "cunning; craftiness")
    //      ("Jingoistic", "extremely patriotic; nationalistic")
    //      ("Nonchalance", "an appearance of indifference; calm and composed")
    //      ("Phlegmatic", "calm; imperturbable")
    //      ("Redress", "put right something that was wrong")
    //      ("Surreptitiously", "secretly; furtively; stealthily")
    //      ("Wily", "cunning")

    //      ("Benign", "kindly; harmless")
    //      ("Contumacious", "stubborn")
    //      ("Embroil", "involve in hostility or argument")
    //      ("Guileless", "frank; straightforward; honest")
    //      ("Jocular", "in a joking manner")
    //      ("Nondescript", "having no special features; dull and ordinary")
    //      ("Pillage", "plunder")
    //      ("Redundant", "unnecessary; superfluous")
    //      ("Susceptible", "vulnerable")
    //      ("Wispy", "flimsy; frail; delicate")

    //      ("Benignity", "compassion; gentleness; fondness")
    //      ("Contusion", "a bruise")
    //      ("Emerge", "come out; appear")
    //      ("Gullibility", "unwariness; trustfulness; being easily fooled")
    //      ("Jollity", "gaiety; happiness")
    //      ("Nonentity", "a person of no importance; not famous")
    //      ("Pinnacle", "topmost point")
    //      ("Referendum", "public vote")
    //      ("Suspect", "doubtful")
    //      ("Wistful", "melancholy; pensive; expressing a longing for")

    //      ("Bequeath", "leave something in one's will to be given after one's death")
    //      ("Conundrum", "a puzzle")
    //      ("Emulate", "to imitate something admired")
    //      ("Gullible", "easily fooled")
    //      ("Jubilant", "ecstatic; delighted; rejoicing")
    //      ("Nostalgia", "longing for the past")
    //      ("Pious", "very religious")
    //      ("Refute", "disprove")
    //      ("Sybarite", "lover of luxury")
    //      ("Zany", "crazy; wacky")

    //      ("Berate", "scold; criticize")
    //      ("Conventional", "usual; customary; common")
    //      ("Endorse", "give support or approval to")
    //      ("Gustatory", "concerned with the sense of taste")
    //      ("Judicious", "correct in judgment; wise")
    //      ("Notoriety", "infamy; known for wrong doing")
    //      ("Pivotal", "of central importance")
    //      ("Regale", "entertain")
    //      ("Sycophant", "bootlicker; flatterer")
    //      ("Zeal", "enthusiasm")

    //      ("Beret", "type of cap")
    //      ("Corpulent", "fat")
    //      ("Endurance", "staying power; patience; stamina")
    //      ("Hackneyed", "common and over-used")
    //      ("Jurisprudence", "science or study of law")
    //      ("Novel", "new; unusual")
    //      ("Placate", "pacify; soothe; calm")
    //      ("Relegate", "dismiss to a lower position")
    //      ("Taciturn", "quiet; saying little")
    //      ("Zealot", "fanatic")

    //      ("Bestial", "behaving like a beast; brutal")
    //      ("Corrugated", "highly folded")
    //      ("Enduring", "lasting")
    //      ("Hallowed", "worshipped; consecrated")
    //      ("Juxtapose", "place next to")
    //      ("Novice", "a beginner; tyro")
    //      ("Placebo", "harmless medicine with no effect; dummy medicine")
    //      ("Remorse", "regret; sorrow; contrition")
    //      ("Tactile", "concerned with the sense of touch")
    //      ("Zenith", "summit")

    //      |]
    // let wordsAndMeaningsSorted = wordsAndMeanings |> Array.sortBy fst
    // Array.iter (printfn "%A") Words.WordsList.wordsAndMeaningsSorted
    let wordsAndMeaningsSorted =
        [|
         ("Abasement", "humiliation; degradation")
         ("Abhor", "hate")
         ("Abrasive", "rough; coarse; harsh")
         ("Abrogate", "cancel; deny; repeal")
         ("Absolution", "forgiveness; pardon; release")
         ("Abstain", "desist; go without; withdraw")
         ("Abstemious", "self denying; refraining from indulging")
         ("Abstruse", "difficult to understand; obscure")
         ("Accolade", "tribute; honor; praise")
         ("Acquiesce", "to agree to; give in to")
         ("Acrid", "sharp; pungent (used of smells and tastes)")
         ("Acrophobia", "fear of heights")
         ("Acuity", "sharpness (mental or visual)")
         ("Adamant", "forceful; inflexible")
         ("Adroit", "skilful / skillful")
         ("Adulation", "strong admiration; worship")
         ("Adversity", "hardship")
         ("Advocate", "support")
         ("Aesthetic", "concerning art or beauty")
         ("Affable", "friendly; social; easygoing")
         ("Alacrity", "eagerness; enthusiasm; quickness")
         ("Alchemy", "medieval chemistry; attempt to change base metal into gold")
         ("Alibi", "an excuse that shows someone was not at a crime scene")
         ("Allay", "to lessen")
         ("Alleviate", "make less severe")
         ("Aloof", "distant; detached; cold")
         ("Altruism", "putting others first; being self-sacrificing")
         ("Amass", "accumulate")
         ("Ambiguity", "uncertainty; vagueness")
         ("Ambiguous", "unclear in meaning; can be interpreted in different ways")
         ("Ambivalence", "lack of clarity; wavering; being undecided")
         ("Ambulatory", "able to walk around (used of hospital patients)")
         ("Ameliorate", "make better")
         ("Amelioration", "improvement")
         ("Amiable", "friendly")
         ("Amity", "friendship")
         ("Amorphous", "lacking in shape")
         ("Analgesic", "medicine to combat pain")
         ("Analogous", "comparable")
         ("Anarchy", "chaos; lack of government")
         ("Anecdote", "a brief amusing story")
         ("Animosity", "hatred; antagonism")
         ("Annex", "(n)	a building which is an addition to an existing building")
         ("Annex", "(v)	take possession of; seize; capture")
         ("Anomaly", "something which does not fit in a pattern; irregularity")
         ("Antagonism", "hostility; strong opposition")
         ("Antagonistic", "opposed; hostile; aggressive")
         ("Antediluvian", "outdated; prehistoric; very old-fashioned")
         ("Anthology", "a book which is a collection of poems or stories")
         ("Anthropocentrism", "putting man at the center of one's philosophy")
         ("Antiquated", "outdated; old fashioned")
         ("Apathetic", "indifferent; uninterested; lethargic")
         ("Apathy", "lack of interest or emotion")
         ("Apocryphal", "of doubtful origin")
         ("Appease", "pacify; soothe; calm down; make peace with")
         ("Apprehensive", "worried; fearful")
         ("Arable", "can be cultivated")
         ("Arbitrary", "random; for no definite reason")
         ("Arcane", "obscure; known only to a few people")
         ("Archaic", "ancient; outdated; old fashioned")
         ("Archetype", "classic example of")
         ("Archives", "collections of old records; place of storage of old documents")
         ("Articulate", "clear; lucid; eloquent")
         ("Artifice", "deception; trickery")
         ("Artisan", "craftsman")
         ("Ascetic", "without luxuries; severely simple")
         ("Assiduous", "thorough; diligent")
         ("Assuage", "to calm")
         ("Astute", "perceptive; sharp-witted")
         ("Asylum", "place of refuge or safety")
         ("Atheist", "person who does not believe in God")
         ("Atrophy", "waste away from lack of use")
         ("Attenuate", "weaken")
         ("Augment", "increase; make bigger")
         ("Auspicious", "favorable; promising to turn out well")
         ("Austere", "severely plain")
         ("Aversion", "a dislike of")
         ("Balk", "hinder and prevent; hesitate over")
         ("Banal", "common; dull")
         ("Banality", "ordinariness; dullness")
         ("Bane", "troublesome influence")
         ("Bard", "poet")
         ("Bastion", "fortress; stronghold")
         ("Befuddle", "confuse")
         ("Begrudge", "resent")
         ("Beguile", "mislead; lure")
         ("Belabor", "explain in unnecessary detail")
         ("Beleaguer", "besiege; attack")
         ("Belie", "contradict")
         ("Belittle", "to demean")
         ("Bellicose", "war-like; aggressive")
         ("Belligerent", "aggressive; ready to fight")
         ("Bemoan", "complain about")
         ("Benevolent", "kindly")
         ("Benign", "kindly; harmless")
         ("Benignity", "compassion; gentleness; fondness")
         ("Bequeath", "leave something in one's will to be given after one's death")
         ("Berate", "scold; criticize")
         ("Beret", "type of cap")
         ("Bestial", "behaving like a beast; brutal")
         ("Bigot", "narrow-minded, prejudiced person")
         ("Bilk", "cheat; defraud")
         ("Billowing", "swelling; fluttering; waving")
         ("Blasphemy", "speech which offends religious sentiments")
         ("Blatant", "obvious")
         ("Blighted", "damaged; destroyed; ruined")
         ("Blithe", "free-spirited; carefree")
         ("Blunderbuss", "1. ancient weapon (type of gun); 2. a clumsy person")
         ("Bolster", "support; prop up")
         ("Bombast", "arrogant, pompous language")
         ("Boorish", "ill-mannered")
         ("Bourgeois", "middle class")
         ("Braggart", "someone who boasts")
         ("Brawny", "muscular")
         ("Brevity", "being brief")
         ("Bristle", "to show irritation")
         ("Broach", "start to discuss; approach")
         ("Brusque", "blunt; abrupt")
         ("Bulwark", "fortification; barricade; wall")
         ("Bureaucracy", "officialdom")
         ("Burgeon", "grow; flourish; put forth new shoots")
         ("Burnish", "polish")
         ("Buttress", "strengthen; support")
         ("Byline", "the line that tells you who wrote an article")
         ("Cacophony", "discordant loud noises")
         ("Cajole", "coax")
         ("Caldron", "huge cooking pot")
         ("Callow", "immature")
         ("Candid", "frank; honest")
         ("Candor", "frankness; openness")
         ("Cantankerous", "bad-tempered; quarrelsome")
         ("Capacious", "spacious")
         ("Capitulate", "surrender; give in to")
         ("Carping", "constant criticism")
         ("Cartographer", "person who makes maps")
         ("Castigate", "scold strongly")
         ("Catharsis", "purging of pent-up emotions")
         ("Caucus", "type of private political meeting")
         ("Caustic", "burning")
         ("Cavalcade", "procession of vehicles")
         ("Celerity", "speed")
         ("Censorious", "disapproving; critical")
         ("Censure", "blame")
         ("Cerebral", "intellectual")
         ("Certitude", "certainty")
         ("Charlatan", "trickster who claims knowledge he doesn't have")
         ("Chary", "wary of; cautious about; reluctant to give")
         ("Chastises", "punishes")
         ("Chicanery", "trickery")
         ("Chimerical", "changeable; unstable")
         ("Choleric", "easily angered")
         ("Chronicler", "person who records historical information")
         ("Circuitous", "indirect")
         ("Circumlocution", "using too many words; long-windedness")
         ("Circumscribe", "limit")
         ("Circumspect", "cautious; considering all sides")
         ("Circumvent", "avoid")
         ("Clairvoyant", "psychic; mystic")
         ("Clamor", "shout; scream")
         ("Clandestine", "secret; covert; stealthy")
         ("Clemency", "mercy")
         ("Cliché", "overused expression; something unoriginal")
         ("Clientele", "customers")
         ("Coalesce", "come together; merge")
         ("Coddle", "pamper; fuss over; indulge")
         ("Coercion", "force")
         ("Cogent", "lucid; well argued")
         ("Cogitate", "think over something; ponder")
         ("Collage", "picture made from fragments of other pictures")
         ("Collate", "arrange in order")
         ("Colloquial", "local and informal (used of language)")
         ("Collusion", "plotting and planning")
         ("Commandeer", "take possession of")
         ("Complacent", "self-satisfied; smug")
         ("Compliant", "easy to control; submissive")
         ("Concatenate", "link together")
         ("Concatenation", "linking into chains")
         ("Conciliate", "to bring together; end a dispute")
         ("Concise", "stated in few words")
         ("Condescend", "talk down to")
         ("Condone", "tacitly support; overlook")
         ("Condoning", "overlooking; disregarding; ignoring")
         ("Conflagration", "big fire")
         ("Confound", "confuse")
         ("Congeal", "to solidify")
         ("Congenital", "present from birth")
         ("Connoisseur", "person with refined taste and good judgment")
         ("Consecrate", "dedicate")
         ("Consensus", "general agreement")
         ("Conspicuous", "easily seen; prominent")
         ("Consummate", "complete; total; supremely good")
         ("Contemporary", "living or happening at the same time")
         ("Contrite", "sorry")
         ("Contrition", "sorrow and repentance")
         ("Contumacious", "stubborn")
         ("Contusion", "a bruise")
         ("Conundrum", "a puzzle")
         ("Conventional", "usual; customary; common")
         ("Corpulent", "fat")
         ("Corrugated", "highly folded")
         ("Counterfeit", "fake; false")
         ("Covert", "hidden; undercover")
         ("Cower", "recoil in fear or servility; shrink away from")
         ("Credible", "believable")
         ("Creditable", "praiseworthy")
         ("Credulous", "gullible; ready to believe anything")
         ("Crepuscular", "active at dawn and dusk")
         ("Cringe", "recoil; flinch; shy away")
         ("Cryptic", "puzzling; enigmatic")
         ("Curtail", "cut short")
         ("Cynical", "believing that people act only out of selfish motives")
         ("Debility", "weakness; incapacity")
         ("Debunking", "exposing false claims or myths")
         ("Decathlon", "an athletic competition with ten events")
         ("Decorum", "dignified, correct behavior [decorous (a)]")
         ("Decoy", "lure; trap; trick")
         ("Deference", "respect")
         ("Defoliate", "cause leaves to fall off")
         ("Defunct", "no longer in existence")
         ("Degradation", "deprivation; poverty; debasement")
         ("Deleterious", "harmful")
         ("Deliberate", "to think over deeply")
         ("Delineation", "demarcation; explanation; definition; outlining")
         ("Demur", "hesitate; refuse")
         ("Denounce", "condemn; speak out against")
         ("Deplete", "use up; lessen")
         ("Deplore", "regret")
         ("Depravity", "moral corruption")
         ("Deprecate", "criticize; denounce")
         ("Deride", "ridicule; make fun of; mock")
         ("Derogatory", "uncomplimentary")
         ("Desecrate", "to damage or pollute a holy place")
         ("Desecration", "spoiling something holy")
         ("Desist", "stop; discontinue; cease")
         ("Despondent", "having no hope; miserable")
         ("Destitution", "hardship; poverty; misery")
         ("Deter", "put off; prevent")
         ("Deteriorate", "worsen; decline")
         ("Detrimental", "harmful")
         ("Devoured", "greedily eaten/consumed")
         ("Dexterous", "skilful with hands")
         ("Dichotomy", "a division into two parts")
         ("Didactic", "intended to teach; instructive")
         ("Diffident", "lacking confidence")
         ("Digress", "wander off the subject")
         ("Dike", "dam; embankment")
         ("Dilatory", "slow; falling behind with one's work")
         ("Dilemma", "puzzling situation")
         ("Dilettante", "person who dabbles in a subject without serious study")
         ("Diligent", "hard-working")
         ("Diorama", "model of a scene")
         ("Dirge", "mournful song")
         ("Disapprobation", "disapproval")
         ("Discern", "to distinguish one thing from another")
         ("Discord", "disagreement")
         ("Discordancy", "cacophony; harshness; jarring")
         ("Discrepancy", "something which does not match up; inconsistency")
         ("Discriminate", "to make a clear distinction; see the difference")
         ("Discursiveness", "long windedness; indirectness")
         ("Disdain", "contempt; strong dislike")
         ("Disinterested", "unbiased")
         ("Disparage", "criticize; belittle")
         ("Disparity", "an inequality")
         ("Dispassionate", "neutral; objective")
         ("Disseminating", "circulating; broadcasting; spreading (information)")
         ("Diurnal", "active in daytime")
         ("Divert", "1. entertain; 2. distract; 3. cause a detour")
         ("Docile", "gentle and easily lead")
         ("Dogmatic", "having stubbornly held opinions")
         ("Dolt", "stupid person")
         ("Dotard", "foolish old man")
         ("Drawl", "speak slowly with words running together")
         ("Drivel", "nonsense")
         ("Droll", "dryly amusing")
         ("Drone", "1. monotonous noise (n); 2. to speak with no emotion (v); 3.male bee")
         ("Dubious", "doubtful")
         ("Dupe", "to fool someone")
         ("Dynamic", "lively; vibrant; energetic")
         ("Ebullient", "very lively; cheerful; jovial; happy")
         ("Eccentric", "unusual; quirky; odd")
         ("Eclectic", "taking things from different sources")
         ("Edifice", "building; structure; construction")
         ("Efface", "wipe out; remove all trace of")
         ("Effigy", "a model of a person")
         ("Effusive", "gushing; demonstrative")
         ("Egalitarianism", "belief in equality")
         ("Egregious", "outstandingly, obviously bad")
         ("Egress", "exit")
         ("Eloquent", "fluent and persuasive in speech")
         ("Elucidate", "make clear")
         ("Elusive", "hard to pin down")
         ("Emaciated", "very thin; withered")
         ("Emancipate", "set free")
         ("Embezzle", "defraud; steal")
         ("Embroil", "involve in hostility or argument")
         ("Emerge", "come out; appear")
         ("Emulate", "to imitate something admired")
         ("Endorse", "give support or approval to")
         ("Endurance", "staying power; patience; stamina")
         ("Enduring", "lasting")
         ("Enfranchise", "give voting rights")
         ("Engender", "cause")
         ("Enhance", "improve; make better or clearer")
         ("Enigma", "puzzle; mystery")
         ("Ensconce", "establish firmly in a position")
         ("Enshroud", "cover")
         ("Enunciation", "clear pronunciation; accent; articulation")
         ("Envenom", "to cause bitterness and bad feeling")
         ("Ephemeral", "short-lived")
         ("Epicure", "someone who appreciates good food and drink")
         ("Epistle", "a letter (form of communication)")
         ("Epistolary", "concerned with letters; through correspondence")
         ("Epitomized", "typified; characterized; personified")
         ("Equivocate", "speak ambiguously; avoid telling the truth")
         ("Err", "make a mistake")
         ("Erratic", "wandering; irregular")
         ("Esoteric", "obscure and difficult to understand")
         ("Espouse", "promote; take up; support")
         ("Etymology", "the study of word origins")
         ("Eulogy", "praise")
         ("Euphemism", "a polite phrase to cover something unpleasant")
         ("Euphony", "pleasant sounds")
         ("Evacuate", "vacate; empty; abandon")
         ("Exacerbate", "make worse")
         ("Exasperated", "frustrated; annoyed")
         ("Exceptionable", "very bad (something which we should object to)")
         ("Exculpate", "free someone from blame; pardon; acquit")
         ("Execrable", "very, very bad")
         ("Exegesis", "scholarly explanation or interpretation")
         ("Exemplary", "outstandingly good; setting a fine example")
         ("Exemplify", "to serve as a good example")
         ("Exhaustive", "complete and thorough")
         ("Exonerates", "acquits; absolves; removes blame")
         ("Exorcism", "getting free/rid of; eliminating (especially demons)")
         ("Expatriate", "refugee; emigrant; someone living away from his own country")
         ("Expedient", "convenient; practical")
         ("Expedite", "make faster")
         ("Exposition", "clear explanation")
         ("Extol", "praise")
         ("Extradite", "deport from one country back to the home country")
         ("Extraneous", "irrelevant")
         ("Extrapolate", "extend; predict on the basis of known data")
         ("Extrinsic", "irrelevant; on the outside")
         ("Fallacious", "false")
         ("Falter", "hesitate; waver")
         ("Fanatical", "obsessive; fixated")
         ("Fanaticism", "passion; excessive devotion")
         ("Fastidious", "overly particular; finicky")
         ("Fatuous", "silly; foolish")
         ("Feasible", "possible and practicable")
         ("Fecund", "fertile")
         ("Felicitous", "apt, well-suited for the occasion")
         ("Fervor", "passion; enthusiasm")
         ("Fickle", "unpredictable; whimsical; easily swayed")
         ("Finesse", "skill")
         ("Fitful", "not continuous; stopping and starting")
         ("Flagrant", "clearly wrong")
         ("Flamboyant", "showy; ornate")
         ("Flaunt", "show off; display in a showy manner")
         ("Flippant", "making jokes about serious matters")
         ("Flout", "defy; reject")
         ("Flustered", "worked-up; not calm")
         ("Fly-by-night", "unreliable; disreputable")
         ("Forensic", "concerned with argument or debate (esp. for legal evidence)")
         ("Fortitude", "bravery")
         ("Fortuitous", "happening by chance")
         ("Fractious", "irritable; difficult to control")
         ("Fraudulent", "fake; false")
         ("Frivolous", "not serious")
         ("Frugal", "economical; not wasting anything")
         ("Furrow", "groove")
         ("Furtive", "hidden and secret")
         ("Futile", "useless; hopeless")
         ("Galleon", "ancient type of sailing ship")
         ("Gambol", "frolic; leap; bound")
         ("Garble", "distort; confuse; muddle")
         ("Garish", "gaudy")
         ("Garner", "gather; collect")
         ("Garrulous", "talkative")
         ("Gaunt", "emaciated; bony and angular")
         ("Genre", "a category; type")
         ("Germane", "relevant")
         ("Germinal", "just growing; not developed; immature")
         ("Gibbering", "making meaningless noises")
         ("Glacial", "hostile; unfriendly; cold; icy")
         ("Goad", "prod; urge")
         ("Grate", "(v)	1. to annoy; aggravate; vex; 2. shred")
         ("Gratis", "free of charge; without payment")
         ("Gratuitous", "unwarranted")
         ("Gravity", "seriousness")
         ("Gregarious", "extroverted; sociable; outgoing")
         ("Gritty", "coarse; granular")
         ("Guffaw", "sudden loud laughter")
         ("Guile", "cunning; craftiness")
         ("Guileless", "frank; straightforward; honest")
         ("Gullibility", "unwariness; trustfulness; being easily fooled")
         ("Gullible", "easily fooled")
         ("Gustatory", "concerned with the sense of taste")
         ("Hackneyed", "common and over-used")
         ("Hallowed", "worshipped; consecrated")
         ("Hamper", "hinder; obstruct")
         ("Hangar", "storage area (like garage) for a plane")
         ("Harangue", "noisy, attacking speech")
         ("Harbingers", "indicators; bringers of warnings")
         ("Hasten", "hurry; accelerate; rush")
         ("Haughtiness", "arrogance; pride")
         ("Headstrong", "stubborn; willful")
         ("Hedonism", "self indulgence; pleasure-seeking")
         ("Hedonist", "a pleasure seeker")
         ("Heed", "listen to")
         ("Heresy", "against orthodox opinion")
         ("Hiatus", "interruption; pause")
         ("Hidebound", "rigid in opinions")
         ("Hieroglyphics", "1. picture writing; 2. writing which is difficult to read or enigmatic")
         ("Hinder", "obstruct")
         ("Histrionic", "theatrical; exaggerated")
         ("Hoary", "old")
         ("Hone", "sharpen; increase; whet")
         ("Hyperbole", "grossly exaggerated speech")
         ("Hypochondriac", "a person obsessed with health; having imaginary illnesses")
         ("Hypocritical", "insincere")
         ("Iconoclast", "person who opposes orthodoxy")
         ("Idiosyncrasy", "a personal peculiarity; something unique to an individual")
         ("Ignominious", "shameful")
         ("Ignominy", "shame [ignominious (a) = shameful]")
         ("Illuminate", "to light up or make clear")
         ("Illusory", "deceptive; false; misleading")
         ("Immoderate", "excessive; extreme")
         ("Immutable", "unchanging; permanent")
         ("Impartial", "unbiased; neutral")
         ("Impecunious", "having no money")
         ("Impious", "wicked; profane")
         ("Impoverished", "destitute; poor")
         ("Impromptu", "unrehearsed; spontaneous")
         ("Inadvertent", "not intentional")
         ("Incantation", "chant; invocation; prayer")
         ("Incarceration", "putting in prison")
         ("Incessant", "without stopping")
         ("Incipient", "just beginning")
         ("Inclination", "tendency; a leaning toward")
         ("Incoherent", "not clear")
         ("Incongruous", "not fitting in; out of place")
         ("Inconsequential", "unimportant; insignificant; negligible")
         ("Inconspicuous", "not easily seen; subtle; not noticeable")
         ("Indelible", "cannot be wiped out")
         ("Indifferent", "1. neutral; 2. not outstanding")
         ("Indigenous", "native to a particular area")
         ("Indolence", "laziness")
         ("Inductee", "novice; beginner")
         ("Indulgent", "pampering; satisfying desires")
         ("Inebriation", "drunkenness; intoxication")
         ("Ineffable", "cannot be expressed in words")
         ("Inept", "incompetent; unskilled; useless")
         ("Inertia", "inactivity; lethargy")
         ("Inevitable", "cannot be avoided")
         ("Inexorable", "relentless")
         ("Inexpedient", "not advisable")
         ("Infallible", "perfect; flawless; cannot make mistakes")
         ("Infamous", "famous for something bad")
         ("Infer", "deduce; conclude")
         ("Ingrate", "ungrateful person")
         ("Ingénue", "naïve, unsophisticated person")
         ("Inimical", "hostile")
         ("Innate", "inherited; inborn")
         ("Innocuous", "harmless; inoffensive")
         ("Innovate", "create; introduce something new")
         ("Inscrutable", "mysterious; impenetrable")
         ("Insentient", "unfeeling")
         ("Insipid", "dull; bland; boring")
         ("Instigate", "to start; provoke")
         ("Instigator", "troublemaker; person who entices others to do something")
         ("Insurgent", "a rebel")
         ("Interminable", "never-ending")
         ("Intermittent", "sporadic; irregular")
         ("Intransigence", "stubbornness")
         ("Intransigent", "stubborn; unyielding")
         ("Intrepid", "brave")
         ("Inveterate", "habitual")
         ("Invidious", "arousing envy")
         ("Inviolable", "cannot be invaded")
         ("Irascible", "easily angered")
         ("Ire", "anger [irate (a) = very angry]")
         ("Irksome", "annoying; infuriating")
         ("Ironic", "satiric; unexpected")
         ("Irrational", "unreasonable; absurd")
         ("Irreproachable", "cannot be criticized; perfect")
         ("Irrevocable", "cannot be cancelled; unchangeable")
         ("Itinerant", "nomadic; wandering from place to place")
         ("Jaded", "tired; bored; worn out")
         ("Jargon", "specialized language used by experts")
         ("Jaundiced", "cynical; pessimistic")
         ("Jaunt", "short pleasure trip")
         ("Jeopardize", "put at risk; endanger")
         ("Jingoistic", "extremely patriotic; nationalistic")
         ("Jocular", "in a joking manner")
         ("Jollity", "gaiety; happiness")
         ("Jubilant", "ecstatic; delighted; rejoicing")
         ("Judicious", "correct in judgment; wise")
         ("Jurisprudence", "science or study of law")
         ("Juxtapose", "place next to")
         ("Kindle", "to start a fire")
         ("Knotty", "complex; difficult to solve")
         ("Labyrinth", "a maze")
         ("Labyrinthine", "complicated; highly convoluted")
         ("Laceration", "a cut")
         ("Lachrymose", "tearful; sad")
         ("Lackluster", "dull; monotonous; bland")
         ("Laconic", "using few words; brief; to the point")
         ("Lamentation", "expression of regret or sorrow")
         ("Lampoon", "ridicule; spoof")
         ("Lance", "spear; spike; javelin")
         ("Languid", "tired; slow")
         ("Languish", "decay; fade away; get weaker")
         ("Larceny", "theft; robbery; stealing")
         ("Largess", "generosity")
         ("Laud", "praise")
         ("Lavish", "on a grand scale; wasteful")
         ("Lax", "careless; not strict")
         ("Legend", "1. key to map; 2. myth or story")
         ("Legion", "in large numbers")
         ("Lethargic", "tired; without energy")
         ("Levity", "flippancy; joking about serious matters")
         ("Libertarian", "someone who opposes tyranny")
         ("Liniment", "soothing lotion")
         ("Lithe", "flexible; supple")
         ("Livid", "very angry")
         ("Lobbyist", "person who tries to persuade someone to support a particular cause")
         ("Lofty", "snooty; arrogant; haughty")
         ("Longevity", "long life")
         ("Loquacious", "talkative")
         ("Lucid", "clear")
         ("Ludicrous", "ridiculous; silly")
         ("Lukewarm", "1. unenthusiastic; 2. neither hot nor cold")
         ("Lummox", "clumsy person")
         ("Luscious", "juicy; moist; succulent")
         ("Lynch", "assassinate; kill; illegal hanging")
         ("Machinations", "plots and plans")
         ("Maelstrom", "whirlpool; storm in the ocean")
         ("Magnanimous", "generous; big-hearted")
         ("Magnate", "powerful businessman")
         ("Maladroit", "clumsy; unskillful")
         ("Malady", "illness")
         ("Malediction", "a curse")
         ("Malefactor", "a wrong-doer")
         ("Malinger", "deliberately avoid work; shirk")
         ("Malingerer", "person who deliberately tries to avoid work")
         ("Malleable", "flexible; can be shaped")
         ("Mallet", "1. wooden hammer; 2. stick used for polo")
         ("Manipulatable", "influencable; controllable")
         ("Marred", "damaged; spoiled")
         ("Marshal", "to gather together")
         ("Marsupial", "pouched mammal (like a kangaroo)")
         ("Martinet", "person who believes in strict discipline")
         ("Masochist", "person who intentionally inflicts pain on himself")
         ("Matriarchy", "society governed by women")
         ("Maverick", "a loner")
         ("Meager", "in short supply")
         ("Meander", "wander from side to side")
         ("Mellow", "soft; melodious; ripe")
         ("Menagerie", "collection of animals")
         ("Mendacious", "given to lying")
         ("Mercenary", "concerned only with money")
         ("Mercurial", "volatile; changeable")
         ("Merge", "come together")
         ("Metaphorically", "symbolically; figuratively")
         ("Meticulous", "very careful; painstaking")
         ("Mettle", "courage; bravery; valor")
         ("Milieu", "environment")
         ("Mire", "swamp; muddy ground")
         ("Misanthrope", "hater of the rest of mankind")
         ("Misnomer", "wrong name")
         ("Misogynist", "hater of women")
         ("Misrepresentation", "deliberately deceiving")
         ("Mitigate", "lessen; make less severe")
         ("Modicum", "small amount")
         ("Momentous", "very important")
         ("Monotonous", "dull; unvarying")
         ("Moratorium", "temporary prohibition or halt to activity")
         ("Moribund", "on the point of death")
         ("Morose", "gloomy; bad tempered")
         ("Mundane", "ordinary; worldly")
         ("Munificent", "generous; charitable")
         ("Mutinous", "very rebellious")
         ("Myriad", "in large numbers")
         ("Navigable", "suitable for sailing")
         ("Nebulous", "vague")
         ("Nefarious", "wicked; immoral; disreputable")
         ("Negate", "cancel; deny")
         ("Negligence", "carelessness")
         ("Neologism", "newly coined word")
         ("Nettle", "annoy")
         ("Niggardly", "miserly; stingy")
         ("Nomadic", "wandering from place to place")
         ("Nonchalance", "an appearance of indifference; calm and composed")
         ("Nondescript", "having no special features; dull and ordinary")
         ("Nonentity", "a person of no importance; not famous")
         ("Nostalgia", "longing for the past")
         ("Notoriety", "infamy; known for wrong doing")
         ("Novel", "new; unusual")
         ("Novice", "a beginner; tyro")
         ("Noxious", "harmful; poisonous; lethal")
         ("Nuance", "something subtle; a fine shade of meaning")
         ("Nullify", "to counter; make unimportant")
         ("Nuzzle", "cuddle; snuggle")
         ("Obdurate", "stubborn")
         ("Obfuscate", "deliberately make something difficult to understand")
         ("Objective", "unbiased; not subjective")
         ("Oblique", "indirect; slanting")
         ("Obliterate", "destroy; demolish; eradicate")
         ("Oblivious", "totally unaware")
         ("Obscure", "difficult to understand; partially hidden")
         ("Obscured", "hidden; covered; buried")
         ("Obsequious", "servile; submissive")
         ("Obsession", "a dominating concern")
         ("Obsolete", "no longer valid")
         ("Obstreperous", "noisy and boisterous")
         ("Obtuse", "mentally dull")
         ("Obviate", "avoid; make unnecessary")
         ("Odious", "hateful")
         ("Officious", "domineering; intrusive; meddlesome")
         ("Ogle", "stare at; observe in an obvious manner")
         ("Olfactory", "concerned with the sense of smell")
         ("Ominous", "threatening")
         ("Omnipotent", "all-powerful")
         ("Omniscient", "all-knowing")
         ("Onerous", "burdensome; hard to undertake")
         ("Onus", "burden")
         ("Opaque", "does not let light through")
         ("Opulent", "wealthy; rich; magnificent")
         ("Ordain", "1. destine; 2. confer holy orders on a priest")
         ("Ornate", "highly decorated")
         ("Orthodox", "conventional")
         ("Ossify", "1. turn to bone; 2. become fixed and rigid")
         ("Ostentatious", "showy")
         ("Oust", "push out of a position")
         ("Overt", "obvious; not hidden")
         ("Overwrought", "worked up; in an emotional state")
         ("Palatable", "good to eat; agreeable")
         ("Palisade", "fence made of posts")
         ("Palliative", "a remedy that improves but doesn't cure")
         ("Pallid", "pale")
         ("Palpable", "easily felt; easily perceived")
         ("Panacea", "remedy for all ills")
         ("Paradigm", "1. example; 2. model; 3. way of looking at things")
         ("Paradox", "apparently contradictory statement")
         ("Paragon", "a perfect example")
         ("Paramount", "of supreme importance")
         ("Parasite", "1. scrounger; 2. animal which takes digested food from another")
         ("Parched", "dried up")
         ("Pariah", "an outcast from society")
         ("Parity", "equality")
         ("Parochial", "narrow-minded; concerned only with local matters")
         ("Parody", "a mockery; imitation for ridicule; spoof")
         ("Parry", "ward off; avoid")
         ("Parsimonious", "economical; frugal; thrifty")
         ("Parsimony", "stinginess; frugality; cost-cutting")
         ("Partisan", "biased; one-sided; committed to one group")
         ("Pathos", "evoking sadness or pity")
         ("Patron", "one who give support (usually financial)")
         ("Patronize", "condescend to; behave in an arrogant manner towards")
         ("Paucity", "shortage")
         ("Peccadillo", "minor weakness; trivial offence")
         ("Pedant", "person who insists on strict adherence to rules or narrow learning")
         ("Pedestrian", "common; mundane; banal")
         ("Peerless", "without equal")
         ("Pejorative", "derogatory")
         ("Pellucid", "transparently clear")
         ("Pensive", "in a thoughtful mood; thinking deeply")
         ("Penury", "poverty")
         ("Perceptive", "observant")
         ("Percipient", "perceptive; insightful")
         ("Perdition", "damnation")
         ("Peremptory", "in a commanding manner")
         ("Perfidy", "treachery")
         ("Perfunctory", "superficial; cursory")
         ("Peripatetic", "nomadic; moving from place to place")
         ("Peripheral", "on the edge; not important")
         ("Perjury", "telling lies under oath")
         ("Pernicious", "destructive; harmful")
         ("Perpetuated", "caused to continue")
         ("Perpetuity", "eternity")
         ("Persnickety", "fastidious; fussy")
         ("Personable", "attractive")
         ("Perspicacious", "insightful; sharp; wise")
         ("Perspicacity", "insight")
         ("Pertinent", "relevant")
         ("Peruse", "read carefully")
         ("Pervasive", "spreading everywhere")
         ("Petrify", "1. terrify; 2. turn to stone")
         ("Petulant", "sulky; peevish")
         ("Phenomenon", "an event or happening (plural: phenomena)")
         ("Philanthropy", "charity; love of mankind")
         ("Philistine", "uncultured person")
         ("Phlegmatic", "calm; imperturbable")
         ("Pillage", "plunder")
         ("Pinnacle", "topmost point")
         ("Pious", "very religious")
         ("Pivotal", "of central importance")
         ("Placate", "pacify; soothe; calm")
         ("Placebo", "harmless medicine with no effect; dummy medicine")
         ("Placid", "calm; peaceful")
         ("Plagiarism", "taking credit for someone else's writing or ideas")
         ("Plaintiff", "petitioner (in court of law)")
         ("Plaudit", "statement giving strong praise")
         ("Plausible", "can be believed; reasonable")
         ("Plethora", "an excess")
         ("Pliable", "flexible; not stubborn")
         ("Plumage", "feathers of a bird")
         ("Plummet", "fall suddenly and steeply")
         ("Podium", "raised platform")
         ("Poignant", "deeply moving; strongly affecting the emotions")
         ("Poised", "calm; collected; self-possessed")
         ("Polemical", "causing debate or argument")
         ("Ponderous", "weighty; slow and heavy")
         ("Pontificate", "speak pompously or dogmatically")
         ("Portend", "foretell")
         ("Portent", "a warning sign; omen")
         ("Poseur", "someone who puts on an act")
         ("Posterity", "future generations")
         ("Posthumous", "after death")
         ("Postulate", "hypothesize; propose")
         ("Potable", "suitable for drinking")
         ("Potent", "powerful; compelling; strong")
         ("Pragmatic", "practical")
         ("Pragmatist", "practical person; one who is concerned with usefulness")
         ("Preamble", "introductory material")
         ("Precarious", "unstable; risky")
         ("Precedent", "a previous occurrence used as a guide")
         ("Precept", "guiding principle")
         ("Precinct", "district of a city")
         ("Precipice", "steep slope")
         ("Precipitous", "done in a hurry")
         ("Preclude", "prevent or make impossible")
         ("Precocious", "developing early")
         ("Predecessor", "one who came before")
         ("Predicament", "dilemma; difficult situation")
         ("Preeminent", "famous; outstanding")
         ("Prerogative", "right or privilege")
         ("Prescient", "having fore-knowledge")
         ("Presentiment", "a feeling that something might happen")
         ("Presumptuous", "assuming too much; arrogant")
         ("Pretentious", "pompous; self-important")
         ("Prevaricate", "speak misleadingly and evasively")
         ("Pristine", "unspoiled")
         ("Proclivity", "tendency towards")
         ("Procrastinate", "delay; put off")
         ("Prodigal", "wasteful; extravagant")
         ("Prodigious", "very large")
         ("Profane", "unholy")
         ("Profanity", "swearing; cursing")
         ("Profound", "having deep meaning")
         ("Profundity", "depth")
         ("Proletarian", "member of the working class")
         ("Prolific", "producing a lot")
         ("Proponents", "promoters; supporters")
         ("Prosaic", "dull; boring; ordinary")
         ("Proscribe", "forbid")
         ("Prosody", "study of versification")
         ("Prostration", "1. lying face down; 2. be overcome with extreme weakness")
         ("Protagonist", "main character in film, book, play etc.")
         ("Protean", "changeable")
         ("Protocol", "procedure; code of behavior")
         ("Protégé", "person under protection of, or guided by another")
         ("Provincial", "unsophisticated; narrow-minded")
         ("Prudent", "cautious; wise")
         ("Puerile", "childish")
         ("Punctilious", "paying attention to small details")
         ("Purloin", "steal")
         ("Pusillanimous", "cowardly")
         ("Pyromania", "compulsion to start fires")
         ("Quaff", "drink down quickly")
         ("Quagmire", "marsh; bog")
         ("Quaint", "picturesque")
         ("Quandary", "dilemma; puzzle")
         ("Quarantine", "isolation to prevent the spread of disease")
         ("Quarry", "1. something that is hunted; 2. mine for stone")
         ("Querulous", "always complaining")
         ("Quirk", "oddity")
         ("Ramble", "wander aimlessly")
         ("Ramifications", "branches; subdivisions of a complex system; outcomes")
         ("Rancor", "resentment; animosity; bad feeling")
         ("Rant", "use bombastic language")
         ("Ratify", "approve; consent")
         ("Raucous", "rough and unpleasant (of sounds)")
         ("Raze", "destroy; demolish; tear down")
         ("Rebuttal", "denial")
         ("Recant", "disclaim; retract statement")
         ("Recapitulate", "summarize")
         ("Receptacle", "container; vessel; holder")
         ("Recluse", "someone who cuts himself off from life")
         ("Recuperate", "get better after illness")
         ("Red", "tape	formalities; paperwork; official procedure")
         ("Redolent", "smelling of; giving off odors")
         ("Redress", "put right something that was wrong")
         ("Redundant", "unnecessary; superfluous")
         ("Referendum", "public vote")
         ("Refute", "disprove")
         ("Regale", "entertain")
         ("Relegate", "dismiss to a lower position")
         ("Remorse", "regret; sorrow; contrition")
         ("Remuneration", "payment for work done")
         ("Renown", "fame")
         ("Replete", "full")
         ("Reprehensible", "shameful; very bad")
         ("Reprieve", "a respite; postponement of a sentence")
         ("Repudiate", "shun; eschew")
         ("Rescind", "retract; repeal")
         ("Resignation", "acceptance of fate")
         ("Resolution", "determination")
         ("Resonant", "echoing")
         ("Respite", "a break; intermission")
         ("Resplendent", "shining; glowing")
         ("Restorative", "a tonic")
         ("Retention", "preservation; withholding")
         ("Reticent", "restrained; holding something back; uncommunicative")
         ("Retraction", "withdrawal; cancellation of a statement")
         ("Revere", "worship")
         ("Riddled", "full of (usually full of holes)")
         ("Rife", "common")
         ("Rigor", "thoroughness")
         ("Robust", "strong; healthy; tough")
         ("Rotund", "round")
         ("Ruminate", "think over something; ponder")
         ("Ruse", "trick; stratagem")
         ("Saccharin", "falsely sweet")
         ("Sacrosanct", "very holy; inviolable")
         ("Sagacious", "wise")
         ("Sage", "a wise person")
         ("Salacious", "lecherous; erotic")
         ("Sallow", "yellowish")
         ("Salubrious", "health-giving")
         ("Salutary", "something which teaches you a lesson; beneficial")
         ("Sanctimonious", "hypocritically holy")
         ("Sanction", "give approval to")
         ("Sanguinary", "bloodthirsty; bloody")
         ("Sanguine", "optimistic; cheerful")
         ("Sardonic", "mocking")
         ("Savant", "person with knowledge")
         ("Scale", "to climb")
         ("Scapegoat", "person on whom blame is placed for faults of others")
         ("Scrupulous", "careful; diligent; painstaking")
         ("Scrutinize", "examine carefully")
         ("Scuttle", "sink")
         ("Seminary", "an institution in which priests are trained")
         ("Sensuous", "appealing to the senses")
         ("Sentinel", "guard; sentry")
         ("Sequester", "isolate")
         ("Serendipity", "fortunate coincidence; unsought discovery")
         ("Serene", "calm; peaceful")
         ("Serrated", "jagged; saw-like")
         ("Servile", "overly submissive; groveling")
         ("Skeptical", "doubting; not gullible")
         ("Skirmish", "minor battle")
         ("Sluggard", "slow-moving; lethargic person")
         ("Smelt", "refine an ore")
         ("Smorgasbord", "a Swedish buffet of cold dishes")
         ("Solace", "comfort for grief")
         ("Solicit", "to ask for; seek")
         ("Somnambulist", "sleepwalker")
         ("Soothsayer", "fortuneteller")
         ("Sophomoric", "juvenile; immature")
         ("Soporific", "inducing sleep")
         ("Sparse", "spare; bare; meager")
         ("Specious", "false")
         ("Speckled", "spotted; freckled; dotted")
         ("Sporadic", "not continuous; intermittent")
         ("Spurious", "false")
         ("Stagnant", "still; not moving")
         ("Staid", "dull; sober; serious")
         ("Stanza", "section of a poem")
         ("Staunch", "loyal; faithful; dependable")
         ("Stereotype", "fixed image")
         ("Stevedore", "dockworker")
         ("Stifle", "suppress")
         ("Stoic", "known for fortitude; indifferent to pleasure or pain")
         ("Stoke", "add fuel to; strengthen")
         ("Stolid", "impassive; dull; indifferent")
         ("Stratagem", "plot; plan; trick")
         ("Strident", "loud and harsh")
         ("Stringent", "strict or severe")
         ("Strut", "swagger; show off")
         ("Stupefying", "astonishing; shocking; stunning into silence")
         ("Subpoena", "summons to court")
         ("Substantiate", "give supporting evidence")
         ("Subterfuge", "a trick")
         ("Subtle", "not obvious")
         ("Subversive", "rebellious; revolutionary")
         ("Succinct", "concise")
         ("Suffragist", "someone who campaigns for voting rights")
         ("Supercilious", "proud and haughty")
         ("Superlative", "extremely good; the best")
         ("Surly", "grumpy; rude")
         ("Surreptitious", "secret; sneaky; stealthy")
         ("Surreptitiously", "secretly; furtively; stealthily")
         ("Susceptible", "vulnerable")
         ("Suspect", "doubtful")
         ("Sybarite", "lover of luxury")
         ("Sycophant", "bootlicker; flatterer")
         ("Taciturn", "quiet; saying little")
         ("Tactile", "concerned with the sense of touch")
         ("Talisman", "lucky charm")
         ("Tangent", "going off the main subject")
         ("Tangible", "can be touched")
         ("Tardy", "slow; late; overdue; delayed")
         ("Tawdry", "of little value; gaudy")
         ("Tedium", "boredom")
         ("Temper", "to moderate; soften")
         ("Tenacious", "stubborn; resolute; holding firm to a purpose")
         ("Tentative", "not certain")
         ("Tenuous", "flimsy; not solid")
         ("Terse", "concise; to the point")
         ("Therapeutic", "medicinal; curative")
         ("Thwart", "prevent; frustrate")
         ("Timorous", "cowardly; fearful")
         ("Tirade", "stream of verbal abuse")
         ("Titter", "giggle quietly")
         ("Tome", "large book")
         ("Torpid", "inactive; lazy; stagnant")
         ("Torpor", "dormancy; sluggishness; inactivity")
         ("Totter", "walk unsteadily")
         ("Tractable", "obedient; dutiful; polite")
         ("Tranquil", "peaceful")
         ("Transcribe", "copy")
         ("Transgress", "go astray; disobey; commit a sin")
         ("Transient", "short-lived; ephemeral")
         ("Traverse", "to move across")
         ("Trepidation", "fear")
         ("Trinket", "something of little value; knick-knack")
         ("Trite", "unoriginal; dull")
         ("Trivial", "unimportant")
         ("Truant", "shirker; someone absent without permission")
         ("Truncate", "cut short")
         ("Tumult", "uproar; noise")
         ("Turpitude", "")
         ("Tyro", "novice; beginner")
         ("Ubiquitous", "found everywhere; omnipresent")
         ("Unalloyed", "undiluted; total")
         ("Unctuous", "oily; using excessive flattery")
         ("Undermined", "damaged; attacked")
         ("Underscore", "emphasize")
         ("Unequivocal", "clear; obvious")
         ("Unfetter", "set free")
         ("Unfrock", "to remove a priest from his position")
         ("Unprecedented", "never having happened before")
         ("Unscathed", "unharmed; intact; without a scratch")
         ("Unwitting", "not deliberate; unconscious")
         ("Upbraid", "scold; tell off; reprimand")
         ("Uproarious", "hilarious; hysterical; very funny")
         ("Upshot", "outcome")
         ("Urbane", "sophisticated; suave")
         ("Usurp", "take someone's position (usually by force)")
         ("Utilitarian", "useful")
         ("Utopian", "a believer in an ideal world")
         ("Vacillate", "waver; hesitate")
         ("Vacuous", "empty; silly; meaningless")
         ("Vagrant", "person wandering without a home")
         ("Vapid", "dull; uninspiring")
         ("Variegated", "multicolored; speckled")
         ("Vehemence", "violence; fervor; forcefulness")
         ("Vehement", "forceful")
         ("Venal", "corrupt; can be bribed")
         ("Veneer", "surface coating")
         ("Venerate", "revere; worship")
         ("Venial", "minor; unimportant")
         ("Veracity", "truthfulness")
         ("Verbose", "talkative; long-winded; rambling")
         ("Verbosity", "using too many words")
         ("Vertigo", "dizziness")
         ("Vestigial", "not developed")
         ("Vignette", "small sketch")
         ("Vilification", "blackening someone's name")
         ("Vindicate", "prove right; remove blame")
         ("Virtuoso", "an accomplished musician")
         ("Virulent", "dangerous; harmful")
         ("Vital", "essential; alive; important")
         ("Vitriolic", "corrosive; strongly attacking")
         ("Vivacity", "liveliness; animation")
         ("Vivify", "enliven")
         ("Vociferous", "noisy; loud in speech")
         ("Volatile", "dangerously unstable; evaporates easily")
         ("Voluble", "talkative")
         ("Voluminous", "very large; spacious")
         ("Voracious", "ravenous")
         ("Waive", "surrender; give up")
         ("Wane", "grow less")
         ("Wary", "hesitant; cautious")
         ("Wax", "to increase; to grow")
         ("Waylay", "accost; stop; approach; hinder")
         ("Weighty", "serious")
         ("Whelp", "young dog")
         ("Whet", "sharpen")
         ("Whimsical", "capricious; changeable")
         ("Willful", "stubborn")
         ("Wily", "cunning")
         ("Wispy", "flimsy; frail; delicate")
         ("Wistful", "melancholy; pensive; expressing a longing for")
         ("Zany", "crazy; wacky")
         ("Zeal", "enthusiasm")
         ("Zealot", "fanatic")
         ("Zenith", "summit")
     |]
